# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate index original text with physical files.

$key = q//;
$index{$key} = ''; 
$key = q/aux in annotation/;
$index{$key} = '<A NAME="tex2html540" HREF="node68.html#5024">The <I>View</I> window</A>, '; 
$key = q/recordrecordname/;
$index{$key} = ''; 
$key = q/recordname/;
$index{$key} = '<A NAME="tex2html278" HREF="node41.html#1415">Analysis example: Measuring ST </A>, <A NAME="tex2html466" HREF="node63.html#2428">The <I>File</I> menu</A>, <A NAME="tex2html486" HREF="node64.html#2486">The <I>Load</I> window</A>, <A NAME="tex2html737" HREF="node96.html#3507">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html931" HREF="node135.html#4422">Menu Variables</A>, '; 
$key = q/command-line options<#2225#><tt>-m</tt><#2225#>/;
$index{$key} = '<A NAME="tex2html420" HREF="node60.html#4929">X11 resources for <I>WAVE</I></A>, '; 
$key = q/dbdesc command/;
$index{$key} = '<A NAME="tex2html574" HREF="node70.html#5035">The <I>Properties</I> menu</A>, '; 
$key = q/environment variablesdbcal/;
$index{$key} = '<A NAME="tex2html24" HREF="node7.html#150">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html342" HREF="node53.html#1893">Display calibration</A>, <A NAME="tex2html365" HREF="node59.html#2046"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html490" HREF="node64.html#2497">The <I>Load</I> window</A>, <A NAME="tex2html764" HREF="node99.html#3630">I can't see the </A>, <A NAME="tex2html785" HREF="node103.html#3693">Why are signals too </A>, '; 
$key = q/www/;
$index{$key} = '<A NAME="tex2html677" HREF="node86.html#3247">Obtaining and installing the </A>, '; 
$key = q/annotationchanging many at once/;
$index{$key} = '<A NAME="tex2html195" HREF="node26.html#881">Changing many annotations at </A>, '; 
$key = q/xrm option for wave/;
$index{$key} = '<A NAME="tex2html440" HREF="node60.html#4940">X11 resources for <I>WAVE</I></A>, '; 
$key = q/ld_library_path environment variable/;
$index{$key} = '<A NAME="tex2html744" HREF="node96.html#3521">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/x window systemserver/;
$index{$key} = '<A NAME="tex2html14" HREF="node6.html#118">Introducing <I>WAVE</I></A>, <A NAME="tex2html26" HREF="node7.html#152">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html66" HREF="node9.html#288">A quick look at </A>, '; 
$key = q/full screen grab, in <#5536#><i>wave</i><#5536#><#472#><#472#> 5.0/;
$index{$key} = '<A NAME="tex2html103" HREF="node14.html#4719">A Five-Minute Tour of </A>, '; 
$key = q/spot help/;
$index{$key} = '<A NAME="tex2html130" HREF="node14.html#519">A Five-Minute Tour of </A>, '; 
$key = q/restoring a deleted annotation/;
$index{$key} = '<A NAME="tex2html183" HREF="node23.html#826">Deleting and restoring annotations</A>, '; 
$key = q/cshsetdb/;
$index{$key} = '<A NAME="tex2html43" HREF="node8.html#4683">Notes:</A>, '; 
$key = q/resolutionof printed output/;
$index{$key} = '<A NAME="tex2html292" HREF="node49.html#1680">Standard methods for printing</A>, <A NAME="tex2html304" HREF="node50.html#1718">Creating custom formats for </A>, <A NAME="tex2html709" HREF="node87.html#3339">Setting up a printer </A>, '; 
$key = q/shell variables/;
$index{$key} = 'see environment variables, '; 
$key = q/controls/;
$index{$key} = ''; 
$key = q/x11 resources/;
$index{$key} = '<A NAME="tex2html400" HREF="node60.html#2156">X11 resources for <I>WAVE</I></A>, '; 
$key = q/environment variablesdb/;
$index{$key} = '<A NAME="tex2html22" HREF="node7.html#148">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html78" HREF="node12.html#322">Checking the environment and </A>, <A NAME="tex2html90" HREF="node13.html#353">Starting <I>WAVE</I></A>, <A NAME="tex2html361" HREF="node59.html#2037"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html494" HREF="node64.html#2501">The <I>Load</I> window</A>, <A NAME="tex2html495" HREF="node64.html#2505">The <I>Load</I> window</A>, <A NAME="tex2html748" HREF="node96.html#3538">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html803" HREF="node109.html#3771">Why does <I>WAVE</I> tell </A>, '; 
$key = q/search/;
$index{$key} = '<A NAME="tex2html120" HREF="node14.html#454">A Five-Minute Tour of </A>, <A NAME="tex2html122" HREF="node14.html#479">A Five-Minute Tour of </A>, <A NAME="tex2html453" HREF="node62.html#2381"><I>WAVE</I>'s main window</A>, <A NAME="tex2html456" HREF="node62.html#2390"><I>WAVE</I>'s main window</A>, <A NAME="tex2html458" HREF="node62.html#2401"><I>WAVE</I>'s main window</A>, <A NAME="tex2html583" HREF="node71.html#2841">The <I>Find</I> window</A>, <A NAME="tex2html891" HREF="node126.html#4132">Can <I>WAVE</I> open more </A>, <A NAME="tex2html947" HREF="node142.html#4600">Other keyboard actions</A>, '; 
$key = q/downloading/;
$index{$key} = '<A NAME="tex2html679" HREF="node86.html#3249">Obtaining and installing the </A>, '; 
$key = q/address, ip (internet protocol)/;
$index{$key} = '<A NAME="tex2html59" HREF="node8.html#257">Notes:</A>, <A NAME="tex2html721" HREF="node91.html#3423">How can I use </A>, '; 
$key = q/undeleting an annotation/;
$index{$key} = '<A NAME="tex2html184" HREF="node23.html#827">Deleting and restoring annotations</A>, '; 
$key = q/annotation file/;
$index{$key} = '<A NAME="tex2html808" HREF="node110.html#3799">Where is my annotation </A>, '; 
$key = q/colorsin signal window/;
$index{$key} = '<A NAME="tex2html790" HREF="node104.html#3729">How can I change </A>, '; 
$key = q/scalesamplitude/;
$index{$key} = '<A NAME="tex2html335" HREF="node53.html#1877">Display calibration</A>, <A NAME="tex2html548" HREF="node68.html#2726">The <I>View</I> window</A>, <A NAME="tex2html596" HREF="node76.html#3026">The <I>Scope</I> window</A>, <A NAME="tex2html762" HREF="node99.html#3627">I can't see the </A>, <A NAME="tex2html922" HREF="node133.html#4342">Command-line Options</A>, <A NAME="tex2html926" HREF="node133.html#4351">Command-line Options</A>, <A NAME="tex2html936" HREF="node135.html#4427">Menu Variables</A>, '; 
$key = q/saving edits/;
$index{$key} = '<A NAME="tex2html201" HREF="node28.html#965">Saving your work</A>, <A NAME="tex2html202" HREF="node28.html#969">Saving your work</A>, '; 
$key = q/options<#3644#><tt>-s</tt><#3644#>/;
$index{$key} = '<A NAME="tex2html768" HREF="node100.html#5158">I can't see text </A>, '; 
$key = q/log/;
$index{$key} = ''; 
$key = q/colorsscope window/;
$index{$key} = '<A NAME="tex2html430" HREF="node60.html#2269">X11 resources for <I>WAVE</I></A>, '; 
$key = q/macintosh/;
$index{$key} = '<A NAME="tex2html17" HREF="node6.html#121">Introducing <I>WAVE</I></A>, '; 
$key = q/formatof printed output/;
$index{$key} = '<A NAME="tex2html291" HREF="node49.html#1643">Standard methods for printing</A>, '; 
$key = q/xvgr command/;
$index{$key} = '<A NAME="tex2html667" HREF="node84.html#5103">Other useful software</A>, '; 
$key = q/mousemousemiddle buttonuses for/;
$index{$key} = '<A NAME="tex2html941" HREF="node139.html#4526">Simple mouse actions</A>, '; 
$key = q/backupof annotation file/;
$index{$key} = '<A NAME="tex2html812" HREF="node114.html#3835">How can I undo </A>, '; 
$key = q/path environment variable/;
$index{$key} = '<A NAME="tex2html89" HREF="node13.html#346">Starting <I>WAVE</I></A>, <A NAME="tex2html371" HREF="node59.html#2071"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html739" HREF="node96.html#3511">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/calibration/;
$index{$key} = '<A NAME="tex2html309" HREF="node51.html#1783">Calibration</A>, '; 
$key = q/adus (analog/digital converter units)/;
$index{$key} = '<A NAME="tex2html312" HREF="node51.html#1786">Calibration</A>, '; 
$key = q/telnet command/;
$index{$key} = '<A NAME="tex2html61" HREF="node8.html#4692">Notes:</A>, '; 
$key = q/analyze window/;
$index{$key} = '<A NAME="tex2html194" HREF="node24.html#4778">Markers</A>, <A NAME="tex2html240" HREF="node34.html#4813"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html476" HREF="node63.html#4980">The <I>File</I> menu</A>, <A NAME="tex2html504" HREF="node66.html#4999">The <I>Analyze</I> window</A>, <A NAME="tex2html593" HREF="node76.html#5076">The <I>Scope</I> window</A>, '; 
$key = q/psfd command/;
$index{$key} = '<A NAME="tex2html296" HREF="node50.html#4871">Creating custom formats for </A>, <A NAME="tex2html842" HREF="node121.html#5222">How can I make </A>, '; 
$key = q/db_maxsig/;
$index{$key} = '<A NAME="tex2html887" HREF="node125.html#5250">Can <I>WAVE</I> open more </A>, '; 
$key = q/wave host/;
$index{$key} = '<A NAME="tex2html21" HREF="node6.html#4661">Introducing <I>WAVE</I></A>, <A NAME="tex2html38" HREF="node8.html#4681">Notes:</A>, <A NAME="tex2html56" HREF="node8.html#4689">Notes:</A>, <A NAME="tex2html77" HREF="node11.html#4699">If you need to </A>, <A NAME="tex2html87" HREF="node13.html#4706">Starting <I>WAVE</I></A>, <A NAME="tex2html145" HREF="node14.html#4743">A Five-Minute Tour of </A>, <A NAME="tex2html357" HREF="node59.html#4902"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html604" HREF="node78.html#5081">Necessities</A>, <A NAME="tex2html620" HREF="node79.html#5083">Printers</A>, <A NAME="tex2html643" HREF="node82.html#5087">Data acquisition and digitization</A>, <A NAME="tex2html671" HREF="node86.html#5109">Obtaining and installing the </A>, <A NAME="tex2html719" HREF="node91.html#5136">How can I use </A>, <A NAME="tex2html805" HREF="node109.html#5190">Why does <I>WAVE</I> tell </A>, '; 
$key = q/middle mouse buttonsimulating/;
$index{$key} = '<A NAME="tex2html49" HREF="node8.html#242">Notes:</A>, <A NAME="tex2html727" HREF="node93.html#3471">How can I insert </A>, '; 
$key = q/view window/;
$index{$key} = '<A NAME="tex2html215" HREF="node30.html#4793">Multi-edit mode</A>, <A NAME="tex2html262" HREF="node36.html#4828">Analysis example: Generating a </A>, <A NAME="tex2html338" HREF="node53.html#4888">Display calibration</A>, <A NAME="tex2html449" HREF="node62.html#4951"><I>WAVE</I>'s main window</A>, <A NAME="tex2html531" HREF="node68.html#5015">The <I>View</I> window</A>, <A NAME="tex2html580" HREF="node71.html#5043">The <I>Find</I> window</A>, '; 
$key = q/middle mouse button/;
$index{$key} = ''; 
$key = q/plot2d command/;
$index{$key} = '<A NAME="tex2html282" HREF="node41.html#4842">Analysis example: Measuring ST </A>, <A NAME="tex2html666" HREF="node84.html#5102">Other useful software</A>, '; 
$key = q/embedded header data in signal files/;
$index{$key} = '<A NAME="tex2html862" HREF="node122.html#4026">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/annotator/;
$index{$key} = '<A NAME="tex2html209" HREF="node29.html#4790">Creating an annotation file </A>, '; 
$key = q/environment variableseditor/;
$index{$key} = '<A NAME="tex2html238" HREF="node34.html#1157"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html377" HREF="node59.html#2084"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html436" HREF="node60.html#2285">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html517" HREF="node66.html#2598">The <I>Analyze</I> window</A>, <A NAME="tex2html526" HREF="node67.html#2649">The <I>Log</I> window</A>, <A NAME="tex2html527" HREF="node67.html#2651">The <I>Log</I> window</A>, '; 
$key = q/signaldisplay mode/;
$index{$key} = '<A NAME="tex2html557" HREF="node68.html#2743">The <I>View</I> window</A>, '; 
$key = q/european st-t database/;
$index{$key} = '<A NAME="tex2html640" HREF="node82.html#3140">Data acquisition and digitization</A>, '; 
$key = q/options<#2331#><tt>-default</tt><#2331#>/;
$index{$key} = '<A NAME="tex2html445" HREF="node60.html#4945">X11 resources for <I>WAVE</I></A>, '; 
$key = q/controlsnavigation/;
$index{$key} = '<A NAME="tex2html111" HREF="node14.html#410">A Five-Minute Tour of </A>, '; 
$key = q/resolutionof multi-frequency records/;
$index{$key} = '<A NAME="tex2html854" HREF="node122.html#4008">Can <I>WAVE</I> read digitized </A>, <A NAME="tex2html874" HREF="node123.html#4065">What is ``high-resolution'' mode?</A>, <A NAME="tex2html920" HREF="node133.html#4309">Command-line Options</A>, '; 
$key = q/annotation fileannotation filecreatingmanually/;
$index{$key} = '<A NAME="tex2html207" HREF="node29.html#984">Creating an annotation file </A>, '; 
$key = q/c-shell/;
$index{$key} = '<A NAME="tex2html42" HREF="node8.html#225">Notes:</A>, '; 
$key = q/dbcollate command/;
$index{$key} = '<A NAME="tex2html825" HREF="node119.html#5206">Can <I>WAVE</I> edit signal </A>, <A NAME="tex2html896" HREF="node126.html#5259">Can <I>WAVE</I> open more </A>, '; 
$key = q/scalestime/;
$index{$key} = '<A NAME="tex2html334" HREF="node53.html#1876">Display calibration</A>, <A NAME="tex2html547" HREF="node68.html#2723">The <I>View</I> window</A>, <A NAME="tex2html595" HREF="node76.html#3025">The <I>Scope</I> window</A>, <A NAME="tex2html924" HREF="node133.html#4347">Command-line Options</A>, <A NAME="tex2html934" HREF="node135.html#4425">Menu Variables</A>, '; 
$key = q/names of computers/;
$index{$key} = '<A NAME="tex2html55" HREF="node8.html#249">Notes:</A>, '; 
$key = q/annotationmoving/;
$index{$key} = '<A NAME="tex2html173" HREF="node20.html#803">Moving an annotation</A>, '; 
$key = q/time indicator/;
$index{$key} = '<A NAME="tex2html110" HREF="node14.html#400">A Five-Minute Tour of </A>, '; 
$key = q/options<#4071#><tt>-h</tt><#4071#>/;
$index{$key} = '<A NAME="tex2html878" HREF="node123.html#5244">What is ``high-resolution'' mode?</A>, '; 
$key = q/lpr command/;
$index{$key} = '<A NAME="tex2html383" HREF="node59.html#4915"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html690" HREF="node87.html#5119">Setting up a printer </A>, <A NAME="tex2html703" HREF="node87.html#5122">Setting up a printer </A>, '; 
$key = q/timeabsolute/;
$index{$key} = '<A NAME="tex2html512" HREF="node66.html#2573">The <I>Analyze</I> window</A>, '; 
$key = q/title barunsaved edit indicator/;
$index{$key} = '<A NAME="tex2html470" HREF="node63.html#2437">The <I>File</I> menu</A>, '; 
$key = q/moving through a record/;
$index{$key} = '<A NAME="tex2html113" HREF="node14.html#412">A Five-Minute Tour of </A>, '; 
$key = q/wave command/;
$index{$key} = '<A NAME="tex2html85" HREF="node13.html#4705">Starting <I>WAVE</I></A>, <A NAME="tex2html736" HREF="node96.html#5147">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html918" HREF="node133.html#5280">Command-line Options</A>, '; 
$key = q/options<#2738#><tt>-dpi</tt><#2738#>/;
$index{$key} = '<A NAME="tex2html556" HREF="node68.html#5027">The <I>View</I> window</A>, '; 
$key = q/annotation fileannotation filecreatingusing an external program/;
$index{$key} = '<A NAME="tex2html150" HREF="node15.html#637">Annotation Editing</A>, '; 
$key = q/annotationvs. marker/;
$index{$key} = '<A NAME="tex2html189" HREF="node24.html#850">Markers</A>, '; 
$key = q/deleting an annotation/;
$index{$key} = '<A NAME="tex2html181" HREF="node23.html#824">Deleting and restoring annotations</A>, '; 
$key = q/environment variableshelpdir/;
$index{$key} = '<A NAME="tex2html394" HREF="node59.html#2134"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/reference annotations/;
$index{$key} = '<A NAME="tex2html96" HREF="node13.html#363">Starting <I>WAVE</I></A>, '; 
$key = q/color map/;
$index{$key} = '<A NAME="tex2html770" HREF="node100.html#3649">I can't see text </A>, '; 
$key = q/csh/;
$index{$key} = '<A NAME="tex2html41" HREF="node8.html#4682">Notes:</A>, '; 
$key = q/signal filepreamble in/;
$index{$key} = '<A NAME="tex2html864" HREF="node122.html#4028">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/annotationenabling editing/;
$index{$key} = '<A NAME="tex2html164" HREF="node17.html#730">The <I>Annotation Template</I></A>, '; 
$key = q/environment variableslist of/;
$index{$key} = '<A NAME="tex2html356" HREF="node59.html#2017"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/text cursor/;
$index{$key} = '<A NAME="tex2html115" HREF="node14.html#435">A Five-Minute Tour of </A>, '; 
$key = q/data acquisition/;
$index{$key} = '<A NAME="tex2html613" HREF="node78.html#3081">Necessities</A>, '; 
$key = q/command-line options<#2737#><tt>-dpi</tt><#2737#>/;
$index{$key} = '<A NAME="tex2html555" HREF="node68.html#5026">The <I>View</I> window</A>, '; 
$key = q/environment variablesdisplay/;
$index{$key} = '<A NAME="tex2html62" HREF="node8.html#274">Notes:</A>, <A NAME="tex2html92" HREF="node13.html#355">Starting <I>WAVE</I></A>, <A NAME="tex2html359" HREF="node59.html#2028"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html750" HREF="node96.html#3540">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/environment variableshelppath/;
$index{$key} = '<A NAME="tex2html392" HREF="node59.html#2125"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/oscilloscope display/;
$index{$key} = '<A NAME="tex2html594" HREF="node76.html#3014">The <I>Scope</I> window</A>, '; 
$key = q/wrann command/;
$index{$key} = '<A NAME="tex2html815" HREF="node117.html#5195">Can I edit annotations </A>, '; 
$key = q/sqrs command/;
$index{$key} = '<A NAME="tex2html232" HREF="node33.html#4805">Analyzing Data with <I>WAVE</I></A>, '; 
$key = q/annotationdisplay font/;
$index{$key} = '<A NAME="tex2html434" HREF="node60.html#2281">X11 resources for <I>WAVE</I></A>, '; 
$key = q/block-interleaved signal file/;
$index{$key} = '<A NAME="tex2html851" HREF="node122.html#3992">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/user's guide (on-line)/;
$index{$key} = '<A NAME="tex2html142" HREF="node14.html#571">A Five-Minute Tour of </A>, '; 
$key = q/search template window/;
$index{$key} = '<A NAME="tex2html199" HREF="node27.html#4784">Searching for annotations</A>, <A NAME="tex2html585" HREF="node71.html#5049">The <I>Find</I> window</A>, <A NAME="tex2html590" HREF="node74.html#5062">The <I>Search Template</I> window</A>, '; 
$key = q/file names, vs. record names/;
$index{$key} = '<A NAME="tex2html797" HREF="node108.html#3755">I can't find the </A>, '; 
$key = q/xform command/;
$index{$key} = '<A NAME="tex2html826" HREF="node119.html#5207">Can <I>WAVE</I> edit signal </A>, <A NAME="tex2html859" HREF="node122.html#5232">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/textprint environment variable/;
$index{$key} = '<A NAME="tex2html384" HREF="node59.html#2103"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html502" HREF="node65.html#2528">The <I>Print setup</I> window</A>, <A NAME="tex2html704" HREF="node87.html#3326">Setting up a printer </A>, '; 
$key = q/analysis commands window/;
$index{$key} = '<A NAME="tex2html231" HREF="node33.html#4804">Analyzing Data with <I>WAVE</I></A>, <A NAME="tex2html241" HREF="node34.html#4814"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html256" HREF="node36.html#4825">Analysis example: Generating a </A>, <A NAME="tex2html285" HREF="node41.html#4847">Analysis example: Measuring ST </A>, <A NAME="tex2html293" HREF="node49.html#4868">Standard methods for printing</A>, <A NAME="tex2html375" HREF="node59.html#4914"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html515" HREF="node66.html#5007">The <I>Analyze</I> window</A>, <A NAME="tex2html795" HREF="node106.html#5181">Everything in the <I>Analysis </A>, '; 
$key = q/marker<#1218#><tt>;spmgt;</tt><#1218#>/;
$index{$key} = '<A NAME="tex2html249" HREF="node35.html#4819">Defining a region of </A>, '; 
$key = q/xdefaults file/;
$index{$key} = '<A NAME="tex2html570" HREF="node68.html#5030">The <I>View</I> window</A>, '; 
$key = q/keyboard focus/;
$index{$key} = '<A NAME="tex2html117" HREF="node14.html#439">A Five-Minute Tour of </A>, '; 
$key = q/cmdtool/;
$index{$key} = '<A NAME="tex2html148" HREF="node15.html#4748">Annotation Editing</A>, '; 
$key = q/colors/;
$index{$key} = ''; 
$key = q/stty command/;
$index{$key} = '<A NAME="tex2html794" HREF="node106.html#5180">Everything in the <I>Analysis </A>, '; 
$key = q/menu file/;
$index{$key} = '<A NAME="tex2html236" HREF="node34.html#1139"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html267" HREF="node38.html#1313">Using a customized menu </A>, <A NAME="tex2html294" HREF="node50.html#1692">Creating custom formats for </A>, <A NAME="tex2html475" HREF="node63.html#2450">The <I>File</I> menu</A>, <A NAME="tex2html519" HREF="node66.html#2600">The <I>Analyze</I> window</A>, <A NAME="tex2html520" HREF="node66.html#2616">The <I>Analyze</I> window</A>, '; 
$key = q/marker<#2562#><tt>;spmgt;</tt><#2562#>/;
$index{$key} = '<A NAME="tex2html509" HREF="node66.html#5002">The <I>Analyze</I> window</A>, '; 
$key = q/type menu/;
$index{$key} = '<A NAME="tex2html161" HREF="node17.html#4761">The <I>Annotation Template</I></A>, <A NAME="tex2html227" HREF="node32.html#4801">Creating and using new </A>, '; 
$key = q/environment variableswavemenu/;
$index{$key} = '<A NAME="tex2html266" HREF="node38.html#1312">Using a customized menu </A>, <A NAME="tex2html370" HREF="node59.html#2060"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html478" HREF="node63.html#2453">The <I>File</I> menu</A>, <A NAME="tex2html480" HREF="node63.html#2466">The <I>File</I> menu</A>, '; 
$key = q/printernon-postscript/;
$index{$key} = '<A NAME="tex2html308" HREF="node50.html#1776">Creating custom formats for </A>, <A NAME="tex2html695" HREF="node87.html#3303">Setting up a printer </A>, '; 
$key = q/find window/;
$index{$key} = '<A NAME="tex2html452" HREF="node62.html#4957"><I>WAVE</I>'s main window</A>, <A NAME="tex2html455" HREF="node62.html#4959"><I>WAVE</I>'s main window</A>, <A NAME="tex2html579" HREF="node71.html#5041">The <I>Find</I> window</A>, '; 
$key = q/formatformatof signal fileschanging/;
$index{$key} = '<A NAME="tex2html858" HREF="node122.html#4018">Can <I>WAVE</I> read digitized </A>, <A NAME="tex2html869" HREF="node122.html#4045">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/mgh/mf waveform database/;
$index{$key} = '<A NAME="tex2html642" HREF="node82.html#3142">Data acquisition and digitization</A>, '; 
$key = q/mousemouseleft button/;
$index{$key} = ''; 
$key = q/on-line help/;
$index{$key} = '<A NAME="tex2html129" HREF="node14.html#517">A Five-Minute Tour of </A>, <A NAME="tex2html390" HREF="node59.html#2123"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html447" HREF="node61.html#2341">Summary of <I>WAVE</I>&nbsp;controls</A>, <A NAME="tex2html460" HREF="node62.html#2407"><I>WAVE</I>'s main window</A>, <A NAME="tex2html586" HREF="node72.html#2869">The <I>Help Topics</I> window</A>, <A NAME="tex2html706" HREF="node87.html#3328">Setting up a printer </A>, <A NAME="tex2html731" HREF="node94.html#3484">How do I get </A>, <A NAME="tex2html904" HREF="node132.html#4210">How can I find </A>, '; 
$key = q/resources/;
$index{$key} = '<A NAME="tex2html399" HREF="node60.html#2155">X11 resources for <I>WAVE</I></A>, '; 
$key = q/unitsadc/;
$index{$key} = '<A NAME="tex2html315" HREF="node51.html#1789">Calibration</A>, '; 
$key = q/wave user's guide (on-line)/;
$index{$key} = '<A NAME="tex2html143" HREF="node14.html#4738">A Five-Minute Tour of </A>, '; 
$key = q/libraries/;
$index{$key} = ''; 
$key = q/resolutionof time in annotation files/;
$index{$key} = '<A NAME="tex2html857" HREF="node122.html#4017">Can <I>WAVE</I> read digitized </A>, <A NAME="tex2html882" HREF="node123.html#4083">What is ``high-resolution'' mode?</A>, '; 
$key = q/fontopen look/;
$index{$key} = '<A NAME="tex2html756" HREF="node97.html#3586">Where do I find </A>, '; 
$key = q/microsoft windows/;
$index{$key} = '<A NAME="tex2html18" HREF="node6.html#122">Introducing <I>WAVE</I></A>, '; 
$key = q/mousemouseleft buttonuses for/;
$index{$key} = '<A NAME="tex2html939" HREF="node137.html#4490">General rules for all </A>, <A NAME="tex2html940" HREF="node139.html#4523">Simple mouse actions</A>, '; 
$key = q/signalbaseline/;
$index{$key} = '<A NAME="tex2html320" HREF="node52.html#1798">Signal calibration</A>, '; 
$key = q/multiplexed signal file/;
$index{$key} = '<A NAME="tex2html850" HREF="node122.html#3991">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/options<#3568#><tt>-s</tt><#3568#>/;
$index{$key} = '<A NAME="tex2html754" HREF="node96.html#5152">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/mousemouseright button/;
$index{$key} = ''; 
$key = q/menu variables/;
$index{$key} = '<A NAME="tex2html242" HREF="node34.html#1168"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html243" HREF="node34.html#1173"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html899" HREF="node130.html#4178">How can I use </A>, '; 
$key = q/anntab environment variable/;
$index{$key} = '<A NAME="tex2html223" HREF="node32.html#1076">Creating and using new </A>, <A NAME="tex2html386" HREF="node59.html#2110"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html405" HREF="node60.html#2189">X11 resources for <I>WAVE</I></A>, '; 
$key = q/xdpyinfo command/;
$index{$key} = '<A NAME="tex2html775" HREF="node102.html#5165">How can I get </A>, '; 
$key = q/formatof signal files/;
$index{$key} = '<A NAME="tex2html760" HREF="node99.html#3624">I can't see the </A>, <A NAME="tex2html844" HREF="node122.html#3979">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/meta key/;
$index{$key} = '<A NAME="tex2html264" HREF="node37.html#4830">The signal list</A>, <A NAME="tex2html946" HREF="node141.html#5296">Mouse and keyboard combination </A>, '; 
$key = q/resolutionof adc/;
$index{$key} = '<A NAME="tex2html614" HREF="node78.html#3082">Necessities</A>, '; 
$key = q/command interpreter/;
$index{$key} = '<A NAME="tex2html37" HREF="node8.html#216">Notes:</A>, '; 
$key = q/olvwm/;
$index{$key} = '<A NAME="tex2html29" HREF="node7.html#4666">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html31" HREF="node8.html#4679">Notes:</A>, <A NAME="tex2html75" HREF="node10.html#4697">About window managers</A>, <A NAME="tex2html133" HREF="node14.html#4731">A Five-Minute Tour of </A>, <A NAME="tex2html347" HREF="node55.html#4897">Using the <I>View</I> window</A>, <A NAME="tex2html632" HREF="node81.html#5085">X11 window managers</A>, <A NAME="tex2html654" HREF="node83.html#5094">About Linux</A>, <A NAME="tex2html735" HREF="node94.html#5144">How do I get </A>, '; 
$key = q/x window systemxfree86 server/;
$index{$key} = '<A NAME="tex2html606" HREF="node78.html#3073">Necessities</A>, <A NAME="tex2html628" HREF="node80.html#3111">Remote access requirements</A>, '; 
$key = q/login/;
$index{$key} = '<A NAME="tex2html46" HREF="node8.html#4686">Notes:</A>, <A NAME="tex2html65" HREF="node8.html#4694">Notes:</A>, <A NAME="tex2html269" HREF="node38.html#4831">Using a customized menu </A>, <A NAME="tex2html711" HREF="node87.html#5125">Setting up a printer </A>, '; 
$key = q/variables/;
$index{$key} = ''; 
$key = q/annotationselecting/;
$index{$key} = '<A NAME="tex2html167" HREF="node18.html#750">Selecting an annotation</A>, '; 
$key = q/annotationattached to signal/;
$index{$key} = '<A NAME="tex2html213" HREF="node30.html#996">Multi-edit mode</A>, '; 
$key = q/solaris/;
$index{$key} = '<A NAME="tex2html12" HREF="node6.html#116">Introducing <I>WAVE</I></A>, <A NAME="tex2html600" HREF="node77.html#3055">System Requirements for <I>WAVE</I></A>, <A NAME="tex2html673" HREF="node86.html#3243">Obtaining and installing the </A>, <A NAME="tex2html692" HREF="node87.html#3291">Setting up a printer </A>, '; 
$key = q/printingcommands/;
$index{$key} = '<A NAME="tex2html474" HREF="node63.html#2443">The <I>File</I> menu</A>, '; 
$key = q/hostname/;
$index{$key} = '<A NAME="tex2html54" HREF="node8.html#4688">Notes:</A>, '; 
$key = q/db environment variable/;
$index{$key} = '<A NAME="tex2html23" HREF="node7.html#149">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html79" HREF="node12.html#323">Checking the environment and </A>, <A NAME="tex2html91" HREF="node13.html#354">Starting <I>WAVE</I></A>, <A NAME="tex2html360" HREF="node59.html#2036"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html493" HREF="node64.html#2500">The <I>Load</I> window</A>, <A NAME="tex2html496" HREF="node64.html#2506">The <I>Load</I> window</A>, <A NAME="tex2html747" HREF="node96.html#3537">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html802" HREF="node109.html#3770">Why does <I>WAVE</I> tell </A>, '; 
$key = q/edf (european data format)/;
$index{$key} = '<A NAME="tex2html871" HREF="node122.html#4054">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/installing <#6883#><i>wave</i><#6883#><#3250#><#3250#>/;
$index{$key} = '<A NAME="tex2html680" HREF="node86.html#5110">Obtaining and installing the </A>, '; 
$key = q/formatof graphics files/;
$index{$key} = '<A NAME="tex2html697" HREF="node87.html#3305">Setting up a printer </A>, '; 
$key = q/printingremotely vs. locally/;
$index{$key} = '<A NAME="tex2html712" HREF="node87.html#3358">Setting up a printer </A>, '; 
$key = q/colorssignal window/;
$index{$key} = '<A NAME="tex2html428" HREF="node60.html#2242">X11 resources for <I>WAVE</I></A>, '; 
$key = q/textedit command/;
$index{$key} = '<A NAME="tex2html239" HREF="node34.html#4810"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html257" HREF="node36.html#4826">Analysis example: Generating a </A>, <A NAME="tex2html518" HREF="node66.html#5008">The <I>Analyze</I> window</A>, <A NAME="tex2html529" HREF="node67.html#5013">The <I>Log</I> window</A>, '; 
$key = q/dpi option for wave/;
$index{$key} = '<A NAME="tex2html331" HREF="node53.html#4885">Display calibration</A>, <A NAME="tex2html411" HREF="node60.html#4922">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html554" HREF="node68.html#5025">The <I>View</I> window</A>, <A NAME="tex2html777" HREF="node102.html#5166">How can I get </A>, '; 
$key = q/preamble in signal files/;
$index{$key} = '<A NAME="tex2html863" HREF="node122.html#4027">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/options<#2226#><tt>-m</tt><#2226#>/;
$index{$key} = '<A NAME="tex2html421" HREF="node60.html#4930">X11 resources for <I>WAVE</I></A>, '; 
$key = q/netscape/;
$index{$key} = '<A NAME="tex2html139" HREF="node14.html#568">A Five-Minute Tour of </A>, <A NAME="tex2html662" HREF="node84.html#3218">Other useful software</A>, <A NAME="tex2html906" HREF="node132.html#4212">How can I find </A>, '; 
$key = q/window manager/;
$index{$key} = '<A NAME="tex2html16" HREF="node6.html#120">Introducing <I>WAVE</I></A>, <A NAME="tex2html27" HREF="node7.html#153">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html67" HREF="node9.html#289">A quick look at </A>, <A NAME="tex2html629" HREF="node81.html#3115">X11 window managers</A>, '; 
$key = q/units/;
$index{$key} = ''; 
$key = q/defining annotation types/;
$index{$key} = '<A NAME="tex2html226" HREF="node32.html#1079">Creating and using new </A>, '; 
$key = q/anntab file/;
$index{$key} = '<A NAME="tex2html813" HREF="node115.html#3853">Can I define my </A>, '; 
$key = q/screen dump/;
$index{$key} = '<A NAME="tex2html125" HREF="node14.html#503">A Five-Minute Tour of </A>, <A NAME="tex2html473" HREF="node63.html#2441">The <I>File</I> menu</A>, <A NAME="tex2html838" HREF="node121.html#3940">How can I make </A>, '; 
$key = q/backup/;
$index{$key} = '<A NAME="tex2html204" HREF="node28.html#978">Saving your work</A>, '; 
$key = q/graphics mode/;
$index{$key} = '<A NAME="tex2html414" HREF="node60.html#2217">X11 resources for <I>WAVE</I></A>, '; 
$key = q/command-line options<#2221#><tt>-g</tt><#2221#>/;
$index{$key} = '<A NAME="tex2html417" HREF="node60.html#4926">X11 resources for <I>WAVE</I></A>, '; 
$key = q/creating an annotation file/;
$index{$key} = ''; 
$key = q/annotationsearching for/;
$index{$key} = '<A NAME="tex2html121" HREF="node14.html#455">A Five-Minute Tour of </A>, <A NAME="tex2html123" HREF="node14.html#480">A Five-Minute Tour of </A>, <A NAME="tex2html454" HREF="node62.html#2382"><I>WAVE</I>'s main window</A>, <A NAME="tex2html457" HREF="node62.html#2391"><I>WAVE</I>'s main window</A>, <A NAME="tex2html459" HREF="node62.html#2402"><I>WAVE</I>'s main window</A>, <A NAME="tex2html584" HREF="node71.html#2842">The <I>Find</I> window</A>, <A NAME="tex2html892" HREF="node126.html#4133">Can <I>WAVE</I> open more </A>, <A NAME="tex2html948" HREF="node142.html#4601">Other keyboard actions</A>, '; 
$key = q/term/;
$index{$key} = '<A NAME="tex2html625" HREF="node80.html#3103">Remote access requirements</A>, <A NAME="tex2html725" HREF="node92.html#3466">Can I run <I>WAVE</I> </A>, '; 
$key = q/bxb command/;
$index{$key} = '<A NAME="tex2html888" HREF="node126.html#5252">Can <I>WAVE</I> open more </A>, '; 
$key = q/icccm/;
$index{$key} = '<A NAME="tex2html630" HREF="node81.html#3116">X11 window managers</A>, '; 
$key = q/num in annotation/;
$index{$key} = '<A NAME="tex2html538" HREF="node68.html#5022">The <I>View</I> window</A>, <A NAME="tex2html563" HREF="node68.html#5029">The <I>View</I> window</A>, '; 
$key = q/right mouse button/;
$index{$key} = ''; 
$key = q/environment variablesanntab/;
$index{$key} = '<A NAME="tex2html224" HREF="node32.html#1077">Creating and using new </A>, <A NAME="tex2html387" HREF="node59.html#2111"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html406" HREF="node60.html#2190">X11 resources for <I>WAVE</I></A>, '; 
$key = q/helpdir environment variable/;
$index{$key} = '<A NAME="tex2html393" HREF="node59.html#2133"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/digitizing signals/;
$index{$key} = '<A NAME="tex2html635" HREF="node82.html#3134">Data acquisition and digitization</A>, '; 
$key = q/resdir environment variable/;
$index{$key} = '<A NAME="tex2html397" HREF="node59.html#2145"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/high-resolution mode/;
$index{$key} = '<A NAME="tex2html855" HREF="node122.html#4009">Can <I>WAVE</I> read digitized </A>, <A NAME="tex2html873" HREF="node123.html#4064">What is ``high-resolution'' mode?</A>, '; 
$key = q/region of interest/;
$index{$key} = '<A NAME="tex2html193" HREF="node24.html#860">Markers</A>, <A NAME="tex2html248" HREF="node35.html#1217">Defining a region of </A>, <A NAME="tex2html505" HREF="node66.html#2556">The <I>Analyze</I> window</A>, '; 
$key = q/beginning of region/;
$index{$key} = '<A NAME="tex2html191" HREF="node24.html#858">Markers</A>, '; 
$key = q/annotationreference/;
$index{$key} = '<A NAME="tex2html95" HREF="node13.html#362">Starting <I>WAVE</I></A>, '; 
$key = q/annotationnum/;
$index{$key} = '<A NAME="tex2html537" HREF="node68.html#5021">The <I>View</I> window</A>, '; 
$key = q/options<#1872#><tt>-dpi</tt><#1872#>/;
$index{$key} = '<A NAME="tex2html333" HREF="node53.html#4887">Display calibration</A>, '; 
$key = q/command-line options<#2229#><tt>-o</tt><#2229#>/;
$index{$key} = '<A NAME="tex2html423" HREF="node60.html#4932">X11 resources for <I>WAVE</I></A>, '; 
$key = q/formatof annotation display/;
$index{$key} = '<A NAME="tex2html350" HREF="node55.html#1947">Using the <I>View</I> window</A>, <A NAME="tex2html560" HREF="node68.html#2752">The <I>View</I> window</A>, '; 
$key = q/level window/;
$index{$key} = '<A NAME="tex2html591" HREF="node75.html#5071">The <I>Level</I> window</A>, '; 
$key = q/fax output/;
$index{$key} = '<A NAME="tex2html696" HREF="node87.html#3304">Setting up a printer </A>, '; 
$key = q/pc/;
$index{$key} = '<A NAME="tex2html20" HREF="node6.html#124">Introducing <I>WAVE</I></A>, <A NAME="tex2html603" HREF="node77.html#3058">System Requirements for <I>WAVE</I></A>, <A NAME="tex2html608" HREF="node78.html#3076">Necessities</A>, <A NAME="tex2html676" HREF="node86.html#3246">Obtaining and installing the </A>, '; 
$key = q/pschart command/;
$index{$key} = '<A NAME="tex2html295" HREF="node50.html#4870">Creating custom formats for </A>, <A NAME="tex2html483" HREF="node63.html#4984">The <I>File</I> menu</A>, <A NAME="tex2html839" HREF="node121.html#5219">How can I make </A>, '; 
$key = q/annotationtable of definitions/;
$index{$key} = '<A NAME="tex2html228" HREF="node32.html#1081">Creating and using new </A>, <A NAME="tex2html388" HREF="node59.html#2112"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html407" HREF="node60.html#2191">X11 resources for <I>WAVE</I></A>, '; 
$key = q/annotator name/;
$index{$key} = '<A NAME="tex2html156" HREF="node16.html#678">Loading annotations to be </A>, <A NAME="tex2html172" HREF="node19.html#800">Changing an annotation without </A>, <A NAME="tex2html211" HREF="node29.html#991">Creating an annotation file </A>, <A NAME="tex2html279" HREF="node41.html#1416">Analysis example: Measuring ST </A>, <A NAME="tex2html467" HREF="node63.html#2429">The <I>File</I> menu</A>, <A NAME="tex2html487" HREF="node64.html#2489">The <I>Load</I> window</A>, <A NAME="tex2html738" HREF="node96.html#3508">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html932" HREF="node135.html#4423">Menu Variables</A>, '; 
$key = q/time scale/;
$index{$key} = '<A NAME="tex2html258" HREF="node36.html#1289">Analysis example: Generating a </A>, <A NAME="tex2html336" HREF="node53.html#1878">Display calibration</A>, <A NAME="tex2html349" HREF="node55.html#1935">Using the <I>View</I> window</A>, <A NAME="tex2html438" HREF="node60.html#2306">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html546" HREF="node68.html#2722">The <I>View</I> window</A>, <A NAME="tex2html597" HREF="node76.html#3027">The <I>Scope</I> window</A>, <A NAME="tex2html923" HREF="node133.html#4346">Command-line Options</A>, <A NAME="tex2html933" HREF="node135.html#4424">Menu Variables</A>, '; 
$key = q/g option for wave/;
$index{$key} = '<A NAME="tex2html416" HREF="node60.html#4925">X11 resources for <I>WAVE</I></A>, '; 
$key = q/display mode/;
$index{$key} = '<A NAME="tex2html415" HREF="node60.html#2218">X11 resources for <I>WAVE</I></A>, '; 
$key = q/h option for wave/;
$index{$key} = '<A NAME="tex2html876" HREF="node123.html#5242">What is ``high-resolution'' mode?</A>, '; 
$key = q/options<#3660#><tt>-s</tt><#3660#>/;
$index{$key} = '<A NAME="tex2html774" HREF="node101.html#5164"><I>WAVE</I> doesn't draw/erase properly </A>, '; 
$key = q/command-line options<#1871#><tt>-dpi</tt><#1871#>/;
$index{$key} = '<A NAME="tex2html332" HREF="node53.html#4886">Display calibration</A>, '; 
$key = q/options<#2207#><tt>-dpi</tt><#2207#>/;
$index{$key} = '<A NAME="tex2html413" HREF="node60.html#4924">X11 resources for <I>WAVE</I></A>, '; 
$key = q/m option for wave/;
$index{$key} = '<A NAME="tex2html419" HREF="node60.html#4928">X11 resources for <I>WAVE</I></A>, '; 
$key = q/options<#2327#><tt>-xrm</tt><#2327#>/;
$index{$key} = '<A NAME="tex2html442" HREF="node60.html#4942">X11 resources for <I>WAVE</I></A>, '; 
$key = q/oversampled signal/;
$index{$key} = '<A NAME="tex2html880" HREF="node123.html#4075">What is ``high-resolution'' mode?</A>, '; 
$key = q/o option for wave/;
$index{$key} = '<A NAME="tex2html422" HREF="node60.html#4931">X11 resources for <I>WAVE</I></A>, '; 
$key = q/keyboard commands/;
$index{$key} = '<A NAME="tex2html175" HREF="node20.html#806">Moving an annotation</A>, '; 
$key = q/multi-edit mode/;
$index{$key} = '<A NAME="tex2html212" HREF="node30.html#995">Multi-edit mode</A>, '; 
$key = q/who am i command/;
$index{$key} = '<A NAME="tex2html57" HREF="node8.html#4690">Notes:</A>, '; 
$key = q/formatof time display/entry/;
$index{$key} = '<A NAME="tex2html351" HREF="node55.html#1958">Using the <I>View</I> window</A>, <A NAME="tex2html564" HREF="node68.html#2763">The <I>View</I> window</A>, <A NAME="tex2html581" HREF="node71.html#2835">The <I>Find</I> window</A>, '; 
$key = q/r option for wave/;
$index{$key} = '<A NAME="tex2html884" HREF="node124.html#5246">Can <I>WAVE</I> open more </A>, '; 
$key = q/annotationmarker bars/;
$index{$key} = '<A NAME="tex2html403" HREF="node60.html#2180">X11 resources for <I>WAVE</I></A>, '; 
$key = q/s option for wave/;
$index{$key} = '<A NAME="tex2html425" HREF="node60.html#4934">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html752" HREF="node96.html#5150">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html766" HREF="node100.html#5156">I can't see text </A>, <A NAME="tex2html772" HREF="node101.html#5162"><I>WAVE</I> doesn't draw/erase properly </A>, <A NAME="tex2html791" HREF="node105.html#5176">Why do colors in </A>, '; 
$key = q/printingon-line help/;
$index{$key} = '<A NAME="tex2html135" HREF="node14.html#560">A Five-Minute Tour of </A>, '; 
$key = q/calibration file/;
$index{$key} = '<A NAME="tex2html157" HREF="node16.html#680">Loading annotations to be </A>, <A NAME="tex2html340" HREF="node53.html#1891">Display calibration</A>, <A NAME="tex2html468" HREF="node63.html#2430">The <I>File</I> menu</A>, <A NAME="tex2html489" HREF="node64.html#2494">The <I>Load</I> window</A>, '; 
$key = q/annotationdeleting/;
$index{$key} = '<A NAME="tex2html180" HREF="node23.html#823">Deleting and restoring annotations</A>, '; 
$key = q/marker<#2641#><tt>:</tt><#2641#>/;
$index{$key} = '<A NAME="tex2html524" HREF="node67.html#5012">The <I>Log</I> window</A>, '; 
$key = q/mousemouseright buttonsimulating/;
$index{$key} = '<A NAME="tex2html51" HREF="node8.html#245">Notes:</A>, <A NAME="tex2html728" HREF="node93.html#3472">How can I insert </A>, '; 
$key = q/timeelapsed/;
$index{$key} = '<A NAME="tex2html508" HREF="node66.html#2559">The <I>Analyze</I> window</A>, '; 
$key = q/menudir environment variable/;
$index{$key} = '<A NAME="tex2html395" HREF="node59.html#2139"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/db_highres/;
$index{$key} = '<A NAME="tex2html856" HREF="node122.html#5230">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/dbcal environment variable/;
$index{$key} = '<A NAME="tex2html25" HREF="node7.html#151">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html341" HREF="node53.html#1892">Display calibration</A>, <A NAME="tex2html364" HREF="node59.html#2045"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html491" HREF="node64.html#2498">The <I>Load</I> window</A>, <A NAME="tex2html763" HREF="node99.html#3629">I can't see the </A>, <A NAME="tex2html784" HREF="node103.html#3692">Why are signals too </A>, '; 
$key = q/setdb/;
$index{$key} = '<A NAME="tex2html44" HREF="node8.html#4684">Notes:</A>, '; 
$key = q/scope window/;
$index{$key} = '<A NAME="tex2html274" HREF="node40.html#4839">Using the <I>Scope</I> window</A>, <A NAME="tex2html429" HREF="node60.html#4937">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html514" HREF="node66.html#5003">The <I>Analyze</I> window</A>, <A NAME="tex2html592" HREF="node76.html#5075">The <I>Scope</I> window</A>, <A NAME="tex2html771" HREF="node101.html#5160"><I>WAVE</I> doesn't draw/erase properly </A>, <A NAME="tex2html898" HREF="node129.html#5264">Can <I>WAVE</I> scroll through </A>, '; 
$key = q/command-line options<#2206#><tt>-dpi</tt><#2206#>/;
$index{$key} = '<A NAME="tex2html412" HREF="node60.html#4923">X11 resources for <I>WAVE</I></A>, '; 
$key = q/command-line options<#2326#><tt>-xrm</tt><#2326#>/;
$index{$key} = '<A NAME="tex2html441" HREF="node60.html#4941">X11 resources for <I>WAVE</I></A>, '; 
$key = q/x terminal/;
$index{$key} = '<A NAME="tex2html633" HREF="node81.html#3128">X11 window managers</A>, '; 
$key = q/windowterminal/;
$index{$key} = '<A NAME="tex2html35" HREF="node8.html#214">Notes:</A>, '; 
$key = q/x window systemclient/;
$index{$key} = '<A NAME="tex2html15" HREF="node6.html#119">Introducing <I>WAVE</I></A>, '; 
$key = q/title bar/;
$index{$key} = '<A NAME="tex2html104" HREF="node14.html#379">A Five-Minute Tour of </A>, <A NAME="tex2html155" HREF="node16.html#677">Loading annotations to be </A>, '; 
$key = q/sunos/;
$index{$key} = '<A NAME="tex2html13" HREF="node6.html#117">Introducing <I>WAVE</I></A>, <A NAME="tex2html601" HREF="node77.html#3056">System Requirements for <I>WAVE</I></A>, <A NAME="tex2html674" HREF="node86.html#3244">Obtaining and installing the </A>, '; 
$key = q/slip/;
$index{$key} = '<A NAME="tex2html624" HREF="node80.html#3102">Remote access requirements</A>, <A NAME="tex2html724" HREF="node92.html#3465">Can I run <I>WAVE</I> </A>, '; 
$key = q/wrsamp command/;
$index{$key} = '<A NAME="tex2html831" HREF="node119.html#5212">Can <I>WAVE</I> edit signal </A>, <A NAME="tex2html868" HREF="node122.html#5238">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/formatof grid display/;
$index{$key} = '<A NAME="tex2html355" HREF="node55.html#1973">Using the <I>View</I> window</A>, <A NAME="tex2html568" HREF="node68.html#2771">The <I>View</I> window</A>, '; 
$key = q/environment variablespath/;
$index{$key} = '<A NAME="tex2html88" HREF="node13.html#345">Starting <I>WAVE</I></A>, <A NAME="tex2html372" HREF="node59.html#2072"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html740" HREF="node96.html#3512">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/command-line options<#4089#><tt>-r</tt><#4089#>/;
$index{$key} = '<A NAME="tex2html885" HREF="node124.html#5247">Can <I>WAVE</I> open more </A>, '; 
$key = q/command-line options<#3739#><tt>-s</tt><#3739#>/;
$index{$key} = '<A NAME="tex2html792" HREF="node105.html#5177">Why do colors in </A>, '; 
$key = q/help window/;
$index{$key} = '<A NAME="tex2html134" HREF="node14.html#531">A Five-Minute Tour of </A>, '; 
$key = q/web browser/;
$index{$key} = '<A NAME="tex2html663" HREF="node84.html#3219">Other useful software</A>, '; 
$key = q/environment variablesmenudir/;
$index{$key} = '<A NAME="tex2html396" HREF="node59.html#2140"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/dragging/;
$index{$key} = '<A NAME="tex2html71" HREF="node10.html#294">About window managers</A>, '; 
$key = q/copying an annotation/;
$index{$key} = '<A NAME="tex2html179" HREF="node22.html#815">Copying an annotation</A>, '; 
$key = q/wavemenu environment variable/;
$index{$key} = '<A NAME="tex2html265" HREF="node38.html#1311">Using a customized menu </A>, <A NAME="tex2html369" HREF="node59.html#2059"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html477" HREF="node63.html#2452">The <I>File</I> menu</A>, <A NAME="tex2html481" HREF="node63.html#2467">The <I>File</I> menu</A>, '; 
$key = q/modem access/;
$index{$key} = '<A NAME="tex2html622" HREF="node80.html#3100">Remote access requirements</A>, <A NAME="tex2html722" HREF="node92.html#3463">Can I run <I>WAVE</I> </A>, '; 
$key = q/signalannotating independently/;
$index{$key} = '<A NAME="tex2html214" HREF="node30.html#997">Multi-edit mode</A>, '; 
$key = q/calibrationsignal/;
$index{$key} = '<A NAME="tex2html324" HREF="node52.html#1836">Signal calibration</A>, <A NAME="tex2html783" HREF="node103.html#3689">Why are signals too </A>, '; 
$key = q/link annotation/;
$index{$key} = '<A NAME="tex2html221" HREF="node31.html#1038">About link annotations</A>, <A NAME="tex2html820" HREF="node118.html#3877">What are `link' annotations?</A>, <A NAME="tex2html949" HREF="node142.html#4635">Other keyboard actions</A>, '; 
$key = q/annotationlink/;
$index{$key} = '<A NAME="tex2html222" HREF="node31.html#1039">About link annotations</A>, <A NAME="tex2html821" HREF="node118.html#3878">What are `link' annotations?</A>, <A NAME="tex2html950" HREF="node142.html#4636">Other keyboard actions</A>, '; 
$key = q/printing/;
$index{$key} = '<A NAME="tex2html616" HREF="node79.html#3091">Printers</A>, '; 
$key = q/mousekeyboard equivalents/;
$index{$key} = '<A NAME="tex2html944" HREF="node140.html#4542">Keyboard equivalents for simple </A>, '; 
$key = q/action buttons/;
$index{$key} = '<A NAME="tex2html149" HREF="node15.html#634">Annotation Editing</A>, <A NAME="tex2html479" HREF="node63.html#2454">The <I>File</I> menu</A>, <A NAME="tex2html521" HREF="node66.html#2617">The <I>Analyze</I> window</A>, '; 
$key = q/time/;
$index{$key} = ''; 
$key = q/logprinting with charts/;
$index{$key} = '<A NAME="tex2html272" HREF="node39.html#1372">Using the <I>Log</I> window</A>, '; 
$key = q/resolution/;
$index{$key} = '<A NAME="tex2html410" HREF="node60.html#2203">X11 resources for <I>WAVE</I></A>, '; 
$key = q/log filereview/;
$index{$key} = '<A NAME="tex2html530" HREF="node67.html#2676">The <I>Log</I> window</A>, '; 
$key = q/x window system/;
$index{$key} = ''; 
$key = q/open lookspot help/;
$index{$key} = '<A NAME="tex2html131" HREF="node14.html#520">A Five-Minute Tour of </A>, '; 
$key = q/annotationrhythm/;
$index{$key} = '<A NAME="tex2html109" HREF="node14.html#395">A Five-Minute Tour of </A>, '; 
$key = q/edit menu/;
$index{$key} = '<A NAME="tex2html450" HREF="node62.html#4953"><I>WAVE</I>'s main window</A>, <A NAME="tex2html571" HREF="node69.html#5032">The <I>Edit</I> menu</A>, '; 
$key = q/signal/;
$index{$key} = ''; 
$key = q/ethernet/;
$index{$key} = '<A NAME="tex2html626" HREF="node80.html#3104">Remote access requirements</A>, <A NAME="tex2html646" HREF="node82.html#3150">Data acquisition and digitization</A>, '; 
$key = q/starting wave/;
$index{$key} = '<A NAME="tex2html84" HREF="node13.html#4704">Starting <I>WAVE</I></A>, <A NAME="tex2html917" HREF="node133.html#5279">Command-line Options</A>, '; 
$key = q/annotationchanging without moving/;
$index{$key} = '<A NAME="tex2html170" HREF="node19.html#782">Changing an annotation without </A>, '; 
$key = q/wave version number/;
$index{$key} = '<A NAME="tex2html578" HREF="node70.html#5039">The <I>Properties</I> menu</A>, '; 
$key = q/log file/;
$index{$key} = '<A NAME="tex2html482" HREF="node63.html#2468">The <I>File</I> menu</A>, <A NAME="tex2html523" HREF="node67.html#2632">The <I>Log</I> window</A>, '; 
$key = q/annotation fileannotation filecreating/;
$index{$key} = ''; 
$key = q/mimic database/;
$index{$key} = '<A NAME="tex2html683" HREF="node86.html#3264">Obtaining and installing the </A>, '; 
$key = q/open look/;
$index{$key} = '<A NAME="tex2html76" HREF="node10.html#307">About window managers</A>, <A NAME="tex2html900" HREF="node131.html#4192">Is there a Motif </A>, <A NAME="tex2html937" HREF="node137.html#4485">General rules for all </A>, '; 
$key = q/command-line options<#2233#><tt>-s</tt><#2233#>/;
$index{$key} = '<A NAME="tex2html426" HREF="node60.html#4935">X11 resources for <I>WAVE</I></A>, '; 
$key = q/options/;
$index{$key} = ''; 
$key = q/annotationrestoring deleted/;
$index{$key} = '<A NAME="tex2html182" HREF="node23.html#825">Deleting and restoring annotations</A>, '; 
$key = q/annotation filebackup/;
$index{$key} = '<A NAME="tex2html205" HREF="node28.html#979">Saving your work</A>, <A NAME="tex2html471" HREF="node63.html#2438">The <I>File</I> menu</A>, <A NAME="tex2html811" HREF="node114.html#3834">How can I undo </A>, '; 
$key = q/xwd command/;
$index{$key} = '<A NAME="tex2html836" HREF="node121.html#5217">How can I make </A>, '; 
$key = q/shared libraries/;
$index{$key} = '<A NAME="tex2html742" HREF="node96.html#3519">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/atr (reference) annotations/;
$index{$key} = '<A NAME="tex2html94" HREF="node13.html#4707">Starting <I>WAVE</I></A>, '; 
$key = q/signalbaselines/;
$index{$key} = '<A NAME="tex2html542" HREF="node68.html#2701">The <I>View</I> window</A>, '; 
$key = q/signalsuppressing display/;
$index{$key} = '<A NAME="tex2html219" HREF="node30.html#1015">Multi-edit mode</A>, '; 
$key = q/dbwhich command/;
$index{$key} = '<A NAME="tex2html806" HREF="node109.html#5191">Why does <I>WAVE</I> tell </A>, '; 
$key = q/formatformatof signal files/;
$index{$key} = ''; 
$key = q/annotation fileloading/;
$index{$key} = '<A NAME="tex2html153" HREF="node16.html#658">Loading annotations to be </A>, '; 
$key = q/signallist/;
$index{$key} = '<A NAME="tex2html220" HREF="node30.html#1016">Multi-edit mode</A>, <A NAME="tex2html247" HREF="node34.html#1214"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html263" HREF="node37.html#1297">The signal list</A>, <A NAME="tex2html513" HREF="node66.html#2580">The <I>Analyze</I> window</A>, <A NAME="tex2html559" HREF="node68.html#2745">The <I>View</I> window</A>, '; 
$key = q/creating an annotation filemanually/;
$index{$key} = '<A NAME="tex2html208" HREF="node29.html#985">Creating an annotation file </A>, '; 
$key = q/file formats/;
$index{$key} = ''; 
$key = q/windowroot/;
$index{$key} = '<A NAME="tex2html33" HREF="node8.html#208">Notes:</A>, '; 
$key = q/display scale/;
$index{$key} = '<A NAME="tex2html261" HREF="node36.html#1292">Analysis example: Generating a </A>, '; 
$key = q/calibrationdisplay/;
$index{$key} = '<A NAME="tex2html329" HREF="node53.html#1865">Display calibration</A>, <A NAME="tex2html553" HREF="node68.html#2734">The <I>View</I> window</A>, <A NAME="tex2html781" HREF="node102.html#3679">How can I get </A>, '; 
$key = q/olwm/;
$index{$key} = '<A NAME="tex2html28" HREF="node7.html#4665">Start-up worksheet for <I>WAVE</I></A>, <A NAME="tex2html30" HREF="node8.html#4678">Notes:</A>, <A NAME="tex2html74" HREF="node10.html#4696">About window managers</A>, <A NAME="tex2html132" HREF="node14.html#4730">A Five-Minute Tour of </A>, <A NAME="tex2html346" HREF="node55.html#4896">Using the <I>View</I> window</A>, <A NAME="tex2html631" HREF="node81.html#5084">X11 window managers</A>, <A NAME="tex2html653" HREF="node83.html#5093">About Linux</A>, <A NAME="tex2html734" HREF="node94.html#5143">How do I get </A>, '; 
$key = q/sample command/;
$index{$key} = '<A NAME="tex2html637" HREF="node82.html#5086">Data acquisition and digitization</A>, <A NAME="tex2html647" HREF="node82.html#5088">Data acquisition and digitization</A>, '; 
$key = q/marker/;
$index{$key} = '<A NAME="tex2html188" HREF="node24.html#847">Markers</A>, '; 
$key = q/mrgann command/;
$index{$key} = '<A NAME="tex2html893" HREF="node126.html#5256">Can <I>WAVE</I> open more </A>, '; 
$key = q/insertion point/;
$index{$key} = '<A NAME="tex2html116" HREF="node14.html#437">A Five-Minute Tour of </A>, '; 
$key = q/markerediting/;
$index{$key} = '<A NAME="tex2html572" HREF="node69.html#2793">The <I>Edit</I> menu</A>, <A NAME="tex2html943" HREF="node139.html#4534">Simple mouse actions</A>, '; 
$key = q/header file/;
$index{$key} = '<A NAME="tex2html317" HREF="node52.html#1795">Signal calibration</A>, <A NAME="tex2html787" HREF="node103.html#3705">Why are signals too </A>, '; 
$key = q/psprint environment variable/;
$index{$key} = '<A NAME="tex2html381" HREF="node59.html#2095"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html500" HREF="node65.html#2526">The <I>Print setup</I> window</A>, <A NAME="tex2html701" HREF="node87.html#3315">Setting up a printer </A>, '; 
$key = q/environment variables/;
$index{$key} = ''; 
$key = q/annotationinserting/;
$index{$key} = '<A NAME="tex2html176" HREF="node21.html#811">Inserting an annotation</A>, '; 
$key = q/physical units/;
$index{$key} = '<A NAME="tex2html313" HREF="node51.html#1787">Calibration</A>, '; 
$key = q/end of region/;
$index{$key} = '<A NAME="tex2html192" HREF="node24.html#859">Markers</A>, '; 
$key = q/on-line manual/;
$index{$key} = '<A NAME="tex2html141" HREF="node14.html#570">A Five-Minute Tour of </A>, '; 
$key = q/printingsignal window contents/;
$index{$key} = '<A NAME="tex2html124" HREF="node14.html#502">A Five-Minute Tour of </A>, <A NAME="tex2html472" HREF="node63.html#2440">The <I>File</I> menu</A>, '; 
$key = q/ppp/;
$index{$key} = '<A NAME="tex2html623" HREF="node80.html#3101">Remote access requirements</A>, <A NAME="tex2html723" HREF="node92.html#3464">Can I run <I>WAVE</I> </A>, '; 
$key = q/open look fonts/;
$index{$key} = '<A NAME="tex2html755" HREF="node97.html#3585">Where do I find </A>, '; 
$key = q/xview/;
$index{$key} = '<A NAME="tex2html389" HREF="node59.html#2121"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html401" HREF="node60.html#2160">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html439" HREF="node60.html#2323">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html652" HREF="node83.html#3172">About Linux</A>, <A NAME="tex2html684" HREF="node86.html#3275">Obtaining and installing the </A>, <A NAME="tex2html715" HREF="node90.html#3395">Can I use <I>WAVE</I> </A>, <A NAME="tex2html733" HREF="node94.html#3489">How do I get </A>, <A NAME="tex2html757" HREF="node97.html#3588">Where do I find </A>, <A NAME="tex2html758" HREF="node97.html#3608">Where do I find </A>, <A NAME="tex2html909" HREF="node132.html#4226">How can I find </A>, '; 
$key = q/annotationcopying/;
$index{$key} = '<A NAME="tex2html178" HREF="node22.html#814">Copying an annotation</A>, '; 
$key = q/xhost command/;
$index{$key} = '<A NAME="tex2html60" HREF="node8.html#4691">Notes:</A>, '; 
$key = q/click-to-type policy/;
$index{$key} = '<A NAME="tex2html73" HREF="node10.html#300">About window managers</A>, '; 
$key = q/file menu/;
$index{$key} = '<A NAME="tex2html448" HREF="node62.html#4949"><I>WAVE</I>'s main window</A>, <A NAME="tex2html464" HREF="node63.html#4972">The <I>File</I> menu</A>, '; 
$key = q/marker<#1219#><tt>;spmlt;</tt><#1219#>/;
$index{$key} = '<A NAME="tex2html250" HREF="node35.html#4820">Defining a region of </A>, '; 
$key = q/shell/;
$index{$key} = '<A NAME="tex2html36" HREF="node8.html#215">Notes:</A>, '; 
$key = q/librariesmissing/;
$index{$key} = '<A NAME="tex2html743" HREF="node96.html#3520">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/focus-follows-mouse policy/;
$index{$key} = '<A NAME="tex2html72" HREF="node10.html#298">About window managers</A>, '; 
$key = q/xpr command/;
$index{$key} = '<A NAME="tex2html837" HREF="node121.html#5218">How can I make </A>, '; 
$key = q/postscript/;
$index{$key} = '<A NAME="tex2html126" HREF="node14.html#504">A Five-Minute Tour of </A>, <A NAME="tex2html305" HREF="node50.html#1723">Creating custom formats for </A>, <A NAME="tex2html307" HREF="node50.html#1775">Creating custom formats for </A>, <A NAME="tex2html380" HREF="node59.html#2091"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html617" HREF="node79.html#3092">Printers</A>, <A NAME="tex2html691" HREF="node87.html#3290">Setting up a printer </A>, <A NAME="tex2html694" HREF="node87.html#3302">Setting up a printer </A>, <A NAME="tex2html716" HREF="node90.html#3401">Can I use <I>WAVE</I> </A>, <A NAME="tex2html835" HREF="node121.html#3937">How can I make </A>, <A NAME="tex2html901" HREF="node132.html#4198">How can I find </A>, '; 
$key = q/shortcut/;
$index{$key} = '<A NAME="tex2html197" HREF="node26.html#884">Changing many annotations at </A>, '; 
$key = q/root window/;
$index{$key} = '<A NAME="tex2html32" HREF="node8.html#207">Notes:</A>, '; 
$key = q/mousemousemiddle buttonsimulating/;
$index{$key} = '<A NAME="tex2html48" HREF="node8.html#241">Notes:</A>, <A NAME="tex2html726" HREF="node93.html#3470">How can I insert </A>, '; 
$key = q/remote access/;
$index{$key} = '<A NAME="tex2html717" HREF="node91.html#3411">How can I use </A>, '; 
$key = q/record/;
$index{$key} = ''; 
$key = q/command-line options/;
$index{$key} = ''; 
$key = q/right mouse buttonsimulating/;
$index{$key} = '<A NAME="tex2html52" HREF="node8.html#246">Notes:</A>, <A NAME="tex2html729" HREF="node93.html#3473">How can I insert </A>, '; 
$key = q/signaloversampled/;
$index{$key} = '<A NAME="tex2html881" HREF="node123.html#4076">What is ``high-resolution'' mode?</A>, '; 
$key = q/cd-rom/;
$index{$key} = '<A NAME="tex2html611" HREF="node78.html#3079">Necessities</A>, <A NAME="tex2html638" HREF="node82.html#3138">Data acquisition and digitization</A>, <A NAME="tex2html809" HREF="node113.html#3821">How do I edit </A>, '; 
$key = q/options<#2222#><tt>-g</tt><#2222#>/;
$index{$key} = '<A NAME="tex2html418" HREF="node60.html#4927">X11 resources for <I>WAVE</I></A>, '; 
$key = q/gnuplot command/;
$index{$key} = '<A NAME="tex2html665" HREF="node84.html#5101">Other useful software</A>, '; 
$key = q/help/;
$index{$key} = '<A NAME="tex2html128" HREF="node14.html#516">A Five-Minute Tour of </A>, <A NAME="tex2html446" HREF="node61.html#2340">Summary of <I>WAVE</I>&nbsp;controls</A>, <A NAME="tex2html732" HREF="node94.html#3485">How do I get </A>, <A NAME="tex2html905" HREF="node132.html#4211">How can I find </A>, '; 
$key = q/file formatssignals/;
$index{$key} = '<A NAME="tex2html845" HREF="node122.html#3980">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/windowsize/;
$index{$key} = '<A NAME="tex2html432" HREF="node60.html#2278">X11 resources for <I>WAVE</I></A>, '; 
$key = q/command-line options<#3643#><tt>-s</tt><#3643#>/;
$index{$key} = '<A NAME="tex2html767" HREF="node100.html#5157">I can't see text </A>, '; 
$key = q/baselines/;
$index{$key} = '<A NAME="tex2html321" HREF="node52.html#1799">Signal calibration</A>, <A NAME="tex2html543" HREF="node68.html#2702">The <I>View</I> window</A>, '; 
$key = q/font/;
$index{$key} = ''; 
$key = q/printerresolution/;
$index{$key} = '<A NAME="tex2html303" HREF="node50.html#1717">Creating custom formats for </A>, <A NAME="tex2html708" HREF="node87.html#3338">Setting up a printer </A>, '; 
$key = q/subtyp in annotation/;
$index{$key} = '<A NAME="tex2html534" HREF="node68.html#5018">The <I>View</I> window</A>, '; 
$key = q/snip command/;
$index{$key} = '<A NAME="tex2html822" HREF="node119.html#5203">Can <I>WAVE</I> edit signal </A>, '; 
$key = q/closing windows/;
$index{$key} = '<A NAME="tex2html138" HREF="node14.html#566">A Five-Minute Tour of </A>, '; 
$key = q/ghostscript/;
$index{$key} = '<A NAME="tex2html619" HREF="node79.html#3094">Printers</A>, <A NAME="tex2html693" HREF="node87.html#3301">Setting up a printer </A>, '; 
$key = q/annotation/;
$index{$key} = ''; 
$key = q/network access/;
$index{$key} = '<A NAME="tex2html621" HREF="node80.html#3099">Remote access requirements</A>, <A NAME="tex2html718" HREF="node91.html#3412">How can I use </A>, '; 
$key = q/inserting an annotation/;
$index{$key} = '<A NAME="tex2html177" HREF="node21.html#812">Inserting an annotation</A>, '; 
$key = q/editundo/;
$index{$key} = '<A NAME="tex2html810" HREF="node114.html#3826">How can I undo </A>, '; 
$key = q/display calibration/;
$index{$key} = '<A NAME="tex2html310" HREF="node51.html#1784">Calibration</A>, <A NAME="tex2html328" HREF="node53.html#1864">Display calibration</A>, <A NAME="tex2html552" HREF="node68.html#2733">The <I>View</I> window</A>, <A NAME="tex2html780" HREF="node102.html#3678">How can I get </A>, '; 
$key = q/environment variablestextprint/;
$index{$key} = '<A NAME="tex2html385" HREF="node59.html#2104"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html503" HREF="node65.html#2529">The <I>Print setup</I> window</A>, <A NAME="tex2html705" HREF="node87.html#3327">Setting up a printer </A>, '; 
$key = q/database path/;
$index{$key} = '<A NAME="tex2html206" HREF="node28.html#981">Saving your work</A>, <A NAME="tex2html469" HREF="node63.html#2431">The <I>File</I> menu</A>, <A NAME="tex2html492" HREF="node64.html#2499">The <I>Load</I> window</A>, '; 
$key = q/finding deleted annotations/;
$index{$key} = '<A NAME="tex2html185" HREF="node23.html#828">Deleting and restoring annotations</A>, '; 
$key = q/marker bars/;
$index{$key} = '<A NAME="tex2html169" HREF="node18.html#766">Selecting an annotation</A>, <A NAME="tex2html404" HREF="node60.html#2181">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html544" HREF="node68.html#2703">The <I>View</I> window</A>, '; 
$key = q/annotationaux/;
$index{$key} = '<A NAME="tex2html539" HREF="node68.html#5023">The <I>View</I> window</A>, '; 
$key = q/chording (mouse technique)/;
$index{$key} = '<A NAME="tex2html50" HREF="node8.html#243">Notes:</A>, <A NAME="tex2html53" HREF="node8.html#247">Notes:</A>, <A NAME="tex2html730" HREF="node93.html#3474">How can I insert </A>, '; 
$key = q/custom menu/;
$index{$key} = 'see menu file, '; 
$key = q/display environment variable/;
$index{$key} = '<A NAME="tex2html93" HREF="node13.html#356">Starting <I>WAVE</I></A>, <A NAME="tex2html358" HREF="node59.html#2027"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html749" HREF="node96.html#3539">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/rdann command/;
$index{$key} = '<A NAME="tex2html82" HREF="node12.html#4702">Checking the environment and </A>, <A NAME="tex2html816" HREF="node117.html#5196">Can I edit annotations </A>, '; 
$key = q/options<#3674#><tt>-dpi</tt><#3674#>/;
$index{$key} = '<A NAME="tex2html779" HREF="node102.html#5168">How can I get </A>, '; 
$key = q/editing shortcuts/;
$index{$key} = '<A NAME="tex2html163" HREF="node17.html#720">The <I>Annotation Template</I></A>, '; 
$key = q/signalnames/;
$index{$key} = '<A NAME="tex2html541" HREF="node68.html#2700">The <I>View</I> window</A>, '; 
$key = q/terminal window/;
$index{$key} = '<A NAME="tex2html34" HREF="node8.html#213">Notes:</A>, <A NAME="tex2html68" HREF="node9.html#290">A quick look at </A>, <A NAME="tex2html86" HREF="node13.html#338">Starting <I>WAVE</I></A>, '; 
$key = q/helpprinting/;
$index{$key} = '<A NAME="tex2html136" HREF="node14.html#561">A Five-Minute Tour of </A>, <A NAME="tex2html588" HREF="node72.html#2877">The <I>Help Topics</I> window</A>, <A NAME="tex2html707" HREF="node87.html#3329">Setting up a printer </A>, '; 
$key = q/signalsignalwindow/;
$index{$key} = ''; 
$key = q/window/;
$index{$key} = ''; 
$key = q/default option for wave/;
$index{$key} = '<A NAME="tex2html443" HREF="node60.html#4943">X11 resources for <I>WAVE</I></A>, '; 
$key = q/scalessetting/;
$index{$key} = '<A NAME="tex2html260" HREF="node36.html#1291">Analysis example: Generating a </A>, '; 
$key = q/log window/;
$index{$key} = '<A NAME="tex2html522" HREF="node67.html#5010">The <I>Log</I> window</A>, '; 
$key = q/moving windows/;
$index{$key} = '<A NAME="tex2html69" HREF="node10.html#292">About window managers</A>, '; 
$key = q/unassigned annotation type codes/;
$index{$key} = '<A NAME="tex2html230" HREF="node32.html#1099">Creating and using new </A>, '; 
$key = q/db software package/;
$index{$key} = '<A NAME="tex2html252" HREF="node36.html#1243">Analysis example: Generating a </A>, <A NAME="tex2html609" HREF="node78.html#3077">Necessities</A>, <A NAME="tex2html660" HREF="node84.html#3194">Other useful software</A>, <A NAME="tex2html678" HREF="node86.html#3248">Obtaining and installing the </A>, '; 
$key = q/start time/;
$index{$key} = '<A NAME="tex2html118" HREF="node14.html#4716">A Five-Minute Tour of </A>, '; 
$key = q/sparcprinter/;
$index{$key} = '<A NAME="tex2html127" HREF="node14.html#505">A Five-Minute Tour of </A>, <A NAME="tex2html618" HREF="node79.html#3093">Printers</A>, '; 
$key = q/mousemousemiddle button/;
$index{$key} = ''; 
$key = q/netscapecolor map problem with/;
$index{$key} = '<A NAME="tex2html769" HREF="node100.html#3648">I can't see text </A>, '; 
$key = q/signal file/;
$index{$key} = ''; 
$key = q/gain/;
$index{$key} = '<A NAME="tex2html318" HREF="node52.html#1796">Signal calibration</A>, '; 
$key = q/ip address/;
$index{$key} = '<A NAME="tex2html58" HREF="node8.html#256">Notes:</A>, <A NAME="tex2html720" HREF="node91.html#3422">How can I use </A>, '; 
$key = q/environment variablesld_library_path/;
$index{$key} = '<A NAME="tex2html745" HREF="node96.html#3522">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/command-line options<#4070#><tt>-h</tt><#4070#>/;
$index{$key} = '<A NAME="tex2html877" HREF="node123.html#5243">What is ``high-resolution'' mode?</A>, '; 
$key = q/changing many annotations/;
$index{$key} = '<A NAME="tex2html196" HREF="node26.html#882">Changing many annotations at </A>, '; 
$key = q/marker<#2557#><tt>;spmlt;</tt><#2557#>/;
$index{$key} = '<A NAME="tex2html506" HREF="node66.html#5001">The <I>Analyze</I> window</A>, '; 
$key = q/index mark/;
$index{$key} = '<A NAME="tex2html190" HREF="node24.html#855">Markers</A>, '; 
$key = q/searchfor deleted annotations/;
$index{$key} = '<A NAME="tex2html187" HREF="node23.html#830">Deleting and restoring annotations</A>, '; 
$key = q/adc boards/;
$index{$key} = '<A NAME="tex2html612" HREF="node78.html#3080">Necessities</A>, <A NAME="tex2html636" HREF="node82.html#3135">Data acquisition and digitization</A>, '; 
$key = q/printer/;
$index{$key} = ''; 
$key = q/navigation controls/;
$index{$key} = '<A NAME="tex2html112" HREF="node14.html#411">A Five-Minute Tour of </A>, '; 
$key = q/command-line options<#3673#><tt>-dpi</tt><#3673#>/;
$index{$key} = '<A NAME="tex2html778" HREF="node102.html#5167">How can I get </A>, '; 
$key = q/calibrate command/;
$index{$key} = '<A NAME="tex2html325" HREF="node52.html#4882">Signal calibration</A>, '; 
$key = q/edit/;
$index{$key} = ''; 
$key = q/signalcalibration/;
$index{$key} = '<A NAME="tex2html311" HREF="node51.html#1785">Calibration</A>, <A NAME="tex2html323" HREF="node52.html#1835">Signal calibration</A>, <A NAME="tex2html782" HREF="node103.html#3688">Why are signals too </A>, '; 
$key = q/creating an annotation fileusing an external program/;
$index{$key} = '<A NAME="tex2html151" HREF="node15.html#638">Annotation Editing</A>, '; 
$key = q/changing an annotation/;
$index{$key} = '<A NAME="tex2html171" HREF="node19.html#783">Changing an annotation without </A>, '; 
$key = q/display resolution/;
$index{$key} = '<A NAME="tex2html409" HREF="node60.html#2202">X11 resources for <I>WAVE</I></A>, '; 
$key = q/signallevels/;
$index{$key} = '<A NAME="tex2html545" HREF="node68.html#2704">The <I>View</I> window</A>, '; 
$key = q/chan in annotation/;
$index{$key} = '<A NAME="tex2html216" HREF="node30.html#4795">Multi-edit mode</A>, <A NAME="tex2html536" HREF="node68.html#5020">The <I>View</I> window</A>, <A NAME="tex2html562" HREF="node68.html#5028">The <I>View</I> window</A>, '; 
$key = q/amplitude scale/;
$index{$key} = '<A NAME="tex2html259" HREF="node36.html#1290">Analysis example: Generating a </A>, <A NAME="tex2html337" HREF="node53.html#1879">Display calibration</A>, <A NAME="tex2html348" HREF="node55.html#1934">Using the <I>View</I> window</A>, <A NAME="tex2html437" HREF="node60.html#2305">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html549" HREF="node68.html#2727">The <I>View</I> window</A>, <A NAME="tex2html598" HREF="node76.html#3028">The <I>Scope</I> window</A>, <A NAME="tex2html761" HREF="node99.html#3626">I can't see the </A>, <A NAME="tex2html921" HREF="node133.html#4341">Command-line Options</A>, <A NAME="tex2html925" HREF="node133.html#4350">Command-line Options</A>, <A NAME="tex2html935" HREF="node135.html#4426">Menu Variables</A>, '; 
$key = q/mit-bih polysomnographic database/;
$index{$key} = '<A NAME="tex2html641" HREF="node82.html#3141">Data acquisition and digitization</A>, '; 
$key = q/printinglog with charts/;
$index{$key} = '<A NAME="tex2html271" HREF="node39.html#1371">Using the <I>Log</I> window</A>, '; 
$key = q/signalsignalwindowdimensions/;
$index{$key} = '<A NAME="tex2html431" HREF="node60.html#2277">X11 resources for <I>WAVE</I></A>, '; 
$key = q/linux/;
$index{$key} = '<A NAME="tex2html11" HREF="node6.html#115">Introducing <I>WAVE</I></A>, <A NAME="tex2html599" HREF="node77.html#3054">System Requirements for <I>WAVE</I></A>, <A NAME="tex2html627" HREF="node80.html#3110">Remote access requirements</A>, <A NAME="tex2html634" HREF="node82.html#3133">Data acquisition and digitization</A>, <A NAME="tex2html644" HREF="node82.html#3146">Data acquisition and digitization</A>, <A NAME="tex2html648" HREF="node83.html#3164">About Linux</A>, <A NAME="tex2html672" HREF="node86.html#3242">Obtaining and installing the </A>, <A NAME="tex2html686" HREF="node86.html#3280">Obtaining and installing the </A>, <A NAME="tex2html714" HREF="node90.html#3392">Can I use <I>WAVE</I> </A>, '; 
$key = q/windowtitle bar/;
$index{$key} = '<A NAME="tex2html105" HREF="node14.html#380">A Five-Minute Tour of </A>, '; 
$key = q/calibration pulse/;
$index{$key} = '<A NAME="tex2html322" HREF="node52.html#1809">Signal calibration</A>, '; 
$key = q/profile/;
$index{$key} = '<A NAME="tex2html45" HREF="node8.html#4685">Notes:</A>, <A NAME="tex2html64" HREF="node8.html#4693">Notes:</A>, <A NAME="tex2html710" HREF="node87.html#5124">Setting up a printer </A>, '; 
$key = q/helppath environment variable/;
$index{$key} = '<A NAME="tex2html391" HREF="node59.html#2124"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/ms-dos/;
$index{$key} = '<A NAME="tex2html610" HREF="node78.html#3078">Necessities</A>, <A NAME="tex2html645" HREF="node82.html#3147">Data acquisition and digitization</A>, '; 
$key = q/web browsers/;
$index{$key} = '<A NAME="tex2html140" HREF="node14.html#569">A Five-Minute Tour of </A>, '; 
$key = q/recordreloading/;
$index{$key} = '<A NAME="tex2html488" HREF="node64.html#2491">The <I>Load</I> window</A>, '; 
$key = q/annotationchan/;
$index{$key} = '<A NAME="tex2html217" HREF="node30.html#4796">Multi-edit mode</A>, <A NAME="tex2html535" HREF="node68.html#5019">The <I>View</I> window</A>, '; 
$key = q/main control panel/;
$index{$key} = '<A NAME="tex2html106" HREF="node14.html#384">A Five-Minute Tour of </A>, '; 
$key = q/signalwindow/;
$index{$key} = '<A NAME="tex2html107" HREF="node14.html#389">A Five-Minute Tour of </A>, <A NAME="tex2html751" HREF="node96.html#3555">Why won't <I>WAVE</I> run?</A>, <A NAME="tex2html759" HREF="node99.html#3619">I can't see the </A>, <A NAME="tex2html883" HREF="node124.html#4086">Can <I>WAVE</I> open more </A>, '; 
$key = q/annotationdisplay mode/;
$index{$key} = '<A NAME="tex2html561" HREF="node68.html#2753">The <I>View</I> window</A>, '; 
$key = q/load window/;
$index{$key} = '<A NAME="tex2html210" HREF="node29.html#4791">Creating an annotation file </A>, <A NAME="tex2html343" HREF="node53.html#4889">Display calibration</A>, <A NAME="tex2html465" HREF="node63.html#4973">The <I>File</I> menu</A>, <A NAME="tex2html485" HREF="node64.html#4990">The <I>Load</I> window</A>, '; 
$key = q/formatof binary executable files/;
$index{$key} = '<A NAME="tex2html658" HREF="node83.html#3185">About Linux</A>, '; 
$key = q/moving an annotation/;
$index{$key} = '<A NAME="tex2html174" HREF="node20.html#804">Moving an annotation</A>, '; 
$key = q/variablesin <#5867#><i>wave</i><#5867#><#1174#><#1174#> menu file/;
$index{$key} = '<A NAME="tex2html244" HREF="node34.html#4815"><I>WAVE</I>'s menu file</A>, '; 
$key = q/tach command/;
$index{$key} = '<A NAME="tex2html253" HREF="node36.html#4822">Analysis example: Generating a </A>, '; 
$key = q/printer environment variable/;
$index{$key} = '<A NAME="tex2html378" HREF="node59.html#2089"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html498" HREF="node65.html#2524">The <I>Print setup</I> window</A>, <A NAME="tex2html699" HREF="node87.html#3311">Setting up a printer </A>, '; 
$key = q/autosaving/;
$index{$key} = '<A NAME="tex2html814" HREF="node116.html#3861">How can I recover </A>, '; 
$key = q/properties menu/;
$index{$key} = '<A NAME="tex2html451" HREF="node62.html#4955"><I>WAVE</I>'s main window</A>, <A NAME="tex2html573" HREF="node70.html#5034">The <I>Properties</I> menu</A>, '; 
$key = q/annotationsubtyp/;
$index{$key} = '<A NAME="tex2html533" HREF="node68.html#5017">The <I>View</I> window</A>, '; 
$key = q/fontin signal window/;
$index{$key} = '<A NAME="tex2html433" HREF="node60.html#2280">X11 resources for <I>WAVE</I></A>, '; 
$key = q/rdsamp command/;
$index{$key} = '<A NAME="tex2html81" HREF="node12.html#4701">Checking the environment and </A>, <A NAME="tex2html830" HREF="node119.html#5211">Can <I>WAVE</I> edit signal </A>, '; 
$key = q/end time/;
$index{$key} = '<A NAME="tex2html119" HREF="node14.html#4717">A Five-Minute Tour of </A>, '; 
$key = q/environment variablesshell/;
$index{$key} = '<A NAME="tex2html39" HREF="node8.html#221">Notes:</A>, <A NAME="tex2html374" HREF="node59.html#2074"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/loading an annotation file/;
$index{$key} = '<A NAME="tex2html154" HREF="node16.html#659">Loading annotations to be </A>, '; 
$key = q/windowmoving/;
$index{$key} = '<A NAME="tex2html70" HREF="node10.html#293">About window managers</A>, '; 
$key = q/windowmenu button/;
$index{$key} = '<A NAME="tex2html137" HREF="node14.html#565">A Five-Minute Tour of </A>, '; 
$key = q/options<#2230#><tt>-o</tt><#2230#>/;
$index{$key} = '<A NAME="tex2html424" HREF="node60.html#4933">X11 resources for <I>WAVE</I></A>, '; 
$key = q/timedisplay mode/;
$index{$key} = '<A NAME="tex2html354" HREF="node55.html#1961">Using the <I>View</I> window</A>, <A NAME="tex2html565" HREF="node68.html#2764">The <I>View</I> window</A>, <A NAME="tex2html929" HREF="node133.html#4364">Command-line Options</A>, '; 
$key = q/dynamically linked libraries/;
$index{$key} = '<A NAME="tex2html741" HREF="node96.html#3518">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/annotationtype codes/;
$index{$key} = '<A NAME="tex2html229" HREF="node32.html#1098">Creating and using new </A>, '; 
$key = q/annotation template window/;
$index{$key} = '<A NAME="tex2html589" HREF="node73.html#5059">The <I>Annotation Template</I> window</A>, '; 
$key = q/unitsphysical/;
$index{$key} = '<A NAME="tex2html314" HREF="node51.html#1788">Calibration</A>, '; 
$key = q/sumann command/;
$index{$key} = '<A NAME="tex2html576" HREF="node70.html#5037">The <I>Properties</I> menu</A>, '; 
$key = q/environment variablesprinter/;
$index{$key} = '<A NAME="tex2html379" HREF="node59.html#2090"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html499" HREF="node65.html#2525">The <I>Print setup</I> window</A>, <A NAME="tex2html700" HREF="node87.html#3312">Setting up a printer </A>, '; 
$key = q/options<#2234#><tt>-s</tt><#2234#>/;
$index{$key} = '<A NAME="tex2html427" HREF="node60.html#4936">X11 resources for <I>WAVE</I></A>, '; 
$key = q/command-line options<#2330#><tt>-default</tt><#2330#>/;
$index{$key} = '<A NAME="tex2html444" HREF="node60.html#4944">X11 resources for <I>WAVE</I></A>, '; 
$key = q/environment variablesresdir/;
$index{$key} = '<A NAME="tex2html398" HREF="node59.html#2146"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/mit-bih arrhythmia database/;
$index{$key} = '<A NAME="tex2html639" HREF="node82.html#3139">Data acquisition and digitization</A>, '; 
$key = q/scales/;
$index{$key} = '<A NAME="tex2html789" HREF="node104.html#3720">How can I change </A>, '; 
$key = q/selection rectangle/;
$index{$key} = '<A NAME="tex2html168" HREF="node18.html#755">Selecting an annotation</A>, '; 
$key = q/sparcstation/;
$index{$key} = '<A NAME="tex2html19" HREF="node6.html#123">Introducing <I>WAVE</I></A>, <A NAME="tex2html602" HREF="node77.html#3057">System Requirements for <I>WAVE</I></A>, <A NAME="tex2html607" HREF="node78.html#3075">Necessities</A>, <A NAME="tex2html675" HREF="node86.html#3245">Obtaining and installing the </A>, '; 
$key = q/rhythm label/;
$index{$key} = '<A NAME="tex2html108" HREF="node14.html#394">A Five-Minute Tour of </A>, '; 
$key = q/annotator namedefault/;
$index{$key} = '<A NAME="tex2html462" HREF="node62.html#2414"><I>WAVE</I>'s main window</A>, '; 
$key = q/x11 resources<#1078#><tt>wave.anntab</tt><#1078#>/;
$index{$key} = '<A NAME="tex2html225" HREF="node32.html#4800">Creating and using new </A>, '; 
$key = q/command-line options<#3567#><tt>-s</tt><#3567#>/;
$index{$key} = '<A NAME="tex2html753" HREF="node96.html#5151">Why won't <I>WAVE</I> run?</A>, '; 
$key = q/environment variablespsprint/;
$index{$key} = '<A NAME="tex2html382" HREF="node59.html#2096"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html501" HREF="node65.html#2527">The <I>Print setup</I> window</A>, <A NAME="tex2html702" HREF="node87.html#3316">Setting up a printer </A>, '; 
$key = q/resolutionof display/;
$index{$key} = '<A NAME="tex2html330" HREF="node53.html#1868">Display calibration</A>, <A NAME="tex2html408" HREF="node60.html#2201">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html551" HREF="node68.html#2732">The <I>View</I> window</A>, <A NAME="tex2html605" HREF="node78.html#3072">Necessities</A>, <A NAME="tex2html776" HREF="node102.html#3665">How can I get </A>, <A NAME="tex2html879" HREF="node123.html#4074">What is ``high-resolution'' mode?</A>, <A NAME="tex2html919" HREF="node133.html#4295">Command-line Options</A>, '; 
$key = q/signaltype/;
$index{$key} = '<A NAME="tex2html339" HREF="node53.html#1890">Display calibration</A>, '; 
$key = q/editor environment variable/;
$index{$key} = '<A NAME="tex2html237" HREF="node34.html#1156"><I>WAVE</I>'s menu file</A>, <A NAME="tex2html376" HREF="node59.html#2083"><I>WAVE</I>&nbsp;environment variables</A>, <A NAME="tex2html435" HREF="node60.html#2284">X11 resources for <I>WAVE</I></A>, <A NAME="tex2html516" HREF="node66.html#2597">The <I>Analyze</I> window</A>, <A NAME="tex2html525" HREF="node67.html#2648">The <I>Log</I> window</A>, <A NAME="tex2html528" HREF="node67.html#2652">The <I>Log</I> window</A>, '; 
$key = q/annotation filecheckpointing/;
$index{$key} = '<A NAME="tex2html200" HREF="node28.html#958">Saving your work</A>, '; 
$key = q/command-line options<#3659#><tt>-s</tt><#3659#>/;
$index{$key} = '<A NAME="tex2html773" HREF="node101.html#5163"><I>WAVE</I> doesn't draw/erase properly </A>, '; 
$key = q/grid/;
$index{$key} = '<A NAME="tex2html550" HREF="node68.html#2731">The <I>View</I> window</A>, <A NAME="tex2html569" HREF="node68.html#2772">The <I>View</I> window</A>, '; 
$key = q/signalnumber/;
$index{$key} = '<A NAME="tex2html218" HREF="node30.html#1011">Multi-edit mode</A>, <A NAME="tex2html510" HREF="node66.html#2566">The <I>Analyze</I> window</A>, <A NAME="tex2html558" HREF="node68.html#2744">The <I>View</I> window</A>, '; 
$key = q/format/;
$index{$key} = ''; 
$key = q/mouse/;
$index{$key} = ''; 
$key = q/pop-up windows/;
$index{$key} = '<A NAME="tex2html114" HREF="node14.html#423">A Five-Minute Tour of </A>, '; 
$key = q/elapsed time/;
$index{$key} = '<A NAME="tex2html353" HREF="node55.html#1960">Using the <I>View</I> window</A>, <A NAME="tex2html507" HREF="node66.html#2558">The <I>Analyze</I> window</A>, <A NAME="tex2html567" HREF="node68.html#2766">The <I>View</I> window</A>, <A NAME="tex2html928" HREF="node133.html#4363">Command-line Options</A>, '; 
$key = q/absolute time/;
$index{$key} = '<A NAME="tex2html352" HREF="node55.html#1959">Using the <I>View</I> window</A>, <A NAME="tex2html511" HREF="node66.html#2572">The <I>Analyze</I> window</A>, <A NAME="tex2html566" HREF="node68.html#2765">The <I>View</I> window</A>, <A NAME="tex2html927" HREF="node133.html#4362">Command-line Options</A>, '; 
$key = q/annotationediting using <#3866#><tt>emacs</tt><#3866#>/;
$index{$key} = '<A NAME="tex2html817" HREF="node117.html#5197">Can I edit annotations </A>, '; 
$key = q/amplitude scaleon printed output/;
$index{$key} = '<A NAME="tex2html306" HREF="node50.html#1768">Creating custom formats for </A>, '; 
$key = q/annotationmnemonic/;
$index{$key} = '<A NAME="tex2html162" HREF="node17.html#717">The <I>Annotation Template</I></A>, <A NAME="tex2html532" HREF="node68.html#2691">The <I>View</I> window</A>, <A NAME="tex2html582" HREF="node71.html#2839">The <I>Find</I> window</A>, '; 
$key = q/shell environment variable/;
$index{$key} = '<A NAME="tex2html40" HREF="node8.html#222">Notes:</A>, <A NAME="tex2html63" HREF="node8.html#275">Notes:</A>, <A NAME="tex2html373" HREF="node59.html#2073"><I>WAVE</I>&nbsp;environment variables</A>, '; 
$key = q/help topics window/;
$index{$key} = '<A NAME="tex2html461" HREF="node62.html#4966"><I>WAVE</I>'s main window</A>, <A NAME="tex2html587" HREF="node72.html#5054">The <I>Help Topics</I> window</A>, '; 
$key = q/print tag in menu file/;
$index{$key} = '<A NAME="tex2html299" HREF="node50.html#4874">Creating custom formats for </A>, '; 
$key = q/mousemouseright buttonuses for/;
$index{$key} = '<A NAME="tex2html938" HREF="node137.html#4488">General rules for all </A>, <A NAME="tex2html942" HREF="node139.html#4530">Simple mouse actions</A>, '; 
$key = q/locating deleted annotations/;
$index{$key} = '<A NAME="tex2html186" HREF="node23.html#829">Deleting and restoring annotations</A>, '; 
$key = q/print setup window/;
$index{$key} = '<A NAME="tex2html497" HREF="node65.html#4993">The <I>Print setup</I> window</A>, '; 
$key = q/recordrecordnamevs. file name/;
$index{$key} = '<A NAME="tex2html796" HREF="node108.html#3754">I can't find the </A>, '; 
$key = q/options<#4090#><tt>-r</tt><#4090#>/;
$index{$key} = '<A NAME="tex2html886" HREF="node124.html#5248">Can <I>WAVE</I> open more </A>, '; 
$key = q/default menu/;
$index{$key} = '<A NAME="tex2html268" HREF="node38.html#1314">Using a customized menu </A>, '; 
$key = q/signal fileformats/;
$index{$key} = '<A NAME="tex2html846" HREF="node122.html#3981">Can <I>WAVE</I> read digitized </A>, '; 
$key = q/options<#3740#><tt>-s</tt><#3740#>/;
$index{$key} = '<A NAME="tex2html793" HREF="node105.html#5178">Why do colors in </A>, '; 
$key = q/signalselecting/;
$index{$key} = '<A NAME="tex2html275" HREF="node40.html#1403">Using the <I>Scope</I> window</A>, <A NAME="tex2html945" HREF="node141.html#4559">Mouse and keyboard combination </A>, '; 
$key = q/main window/;
$index{$key} = '<A NAME="tex2html97" HREF="node13.html#370">Starting <I>WAVE</I></A>, '; 
$key = q/database path;/;
$index{$key} = '<A NAME="tex2html158" HREF="node16.html#681">Loading annotations to be </A>, '; 
$key = q/signalgain/;
$index{$key} = '<A NAME="tex2html319" HREF="node52.html#1797">Signal calibration</A>, '; 
$key = q/quit button/;
$index{$key} = '<A NAME="tex2html144" HREF="node14.html#4742">A Five-Minute Tour of </A>, <A NAME="tex2html203" HREF="node28.html#4788">Saving your work</A>, <A NAME="tex2html463" HREF="node62.html#4970"><I>WAVE</I>'s main window</A>, '; 

1;

