'\" t
.TH ECGEVAL 1 "20 May 1999" "WFDB software 10.0" "WFDB applications"
.SH NAME
ecgeval \- generate and run ECG analyzer evaluation script
.SH SYNOPSIS
\fBecgeval\fR
.SH DESCRIPTION
.PP
This program generates a Bourne shell (\fIsh\fR(1)) script under UNIX, or
a batch file under MS-DOS, to compare a set of test annotation files with
a set of reference annotation files and a set of reference heart rate
measurement files using the programs \fIbxb\fR(1), \fIrxr\fR(1), \fImxm\fR(1),
and \fIepic\fR(1), and then to produce summary reports by passing the outputs
of these programs to \fIsumstats\fR(1) and \fIplotstm\fR(1).
.PP
\fIecgeval\fR asks interactively for the annotator names, the name of
the database to be used, and which optional analyzer outputs are to be
evaluated.  It then creates the evaluation script, and offers the user a
choice of running the script immediately, or exiting (in order to review
and perhaps edit the script before running it).
.PP
The shell variable \fBWFDB\fR should be set and exported (see \fIsetwfdb\fR(1)).
.SH FILES
.TP
dblist	
This file, which should be located in one of the directories named by \fBWFDB\fR,
contains a list of the available databases.  Each entry is a line containing
three tab-separated fields:  the short name for the database, the name of a
file (which must also be in one of the directories named by \fBWFDB\fR)
containing a list of the record names for the database, and a longer name for
the database.  Empty lines and lines beginning with `#' are ignored.  The
version of this file distributed with the WFDB software package contains:
.TS
center;
l l l.
MIT DB	mitlist	MIT-BIH Arrhythmia Database
MITx DB	mitxlist	MIT-BIH Arrhythmia Database (excluding paced records)
AHA DB	ahalist	AHA Database for Evaluation of Ventricular Arrhythmia Detectors
AHAx DB	ahaxlist	AHA Database (excluding paced records)
ESC DB	esclist	European ST-T Database
NST DB	nstlist	Noise Stress Test Database
CU DB	culist	Creighton University Sustained Ventricular Arrhythmia Database
.TE
.SH SEE ALSO
bxb(1), epic(1), mxm(1), plotstm(1), rxr(1), setwfdb(1), sumstats(1)
.br
\fIEvaluating ECG Analyzers\fR
