.TH RXR 1 "9 February 2000" "WFDB software 10.1" "WFDB applications"
.SH NAME
rxr \- ANSI/AAMI-standard run-by-run annotation comparator
.SH SYNOPSIS
\fBrxr -r \fIrecord\fB -a \fIreference-annotator test-annotator\fR [ \fIoptions ... \fR ]
.SH DESCRIPTION
.PP
Using options \fB-C\fR, \fB-L\fR, or \fB-S\fR, \fIrxr\fR implements the
run-by-run comparison algorithms described in AAMI/ANSI EC38:1998, the American
National Standard for Ambulatory ECGs, and in AAMI EC57:1998, the American
National Standard for Testing and Reporting Performance Results of Cardiac
Rhythm and ST Segment Measurement Algorithms.  \fIrxr\fR is the reference
implementation of these algorithms, and must be used to obtain the run-by-run
performance statistics cited in EC38 and EC57 in order to be in compliance with
the standards (see EC38, section 5.2.14, and EC57, section 4.2).
.PP
Input to this program consists of two annotation files associated with the same
\fIrecord\fR.  One of these is designated the \fIreference\fR annotation file,
the other the \fItest\fR annotation file (called the `algorithm' annotation
file in EC38 and in EC57).
.PP
\fIOptions\fR include:
.TP
\fB-c \fIfile\fR
Append condensed reports to \fIfile\fR.
.TP
\fB-C \fIfile\fR
As for \fB-c\fR, but report SVE run statistics also.
.TP
\fB-f \fItime\fR
Begin the comparison at the specified \fItime\fR (default: 5 minutes after the
beginning of the record).
.TP
\fB-h\fR
Print a usage summary.
.TP
\fB-l \fIfile\fR
Append line-format reports (EC57 Table A.7 format) to \fIfile\fR (see below).
.TP
\fB-L \fIfile file2\fR
As for \fB-l\fR, but report SVE run statistics in \fIfile2\fR.
.TP
\fB-s \fIfile\fR
Append standard reports (EC38 section 5.2.14, EC57 Tables 7, 8 format) to
\fIfile\fR.
.TP
\fB-S \fIfile\fR
As for \fB-s\fR, but report SVE run statistics also.
.TP
\fB-t \fItime\fR
Stop the comparison at the specified \fItime\fR (default: the end of the record
if it is defined, the end of the reference annotation file otherwise;  if
\fItime\fR is 0, the comparison ends when the end of either annotation file is
reached).
.TP
\fB-v\fR
Verbose mode (list all discrepancies;  see below).
.TP
\fB-w \fItime\fR
Set the \fImatch window\fR (default: 0.15 seconds;  see below).
.PP
.PP
At most one of \fB-c\fR, \fB-C\fR, \fB-l\fR, \fB-L\fR, \fB-s\fR, and \fB-S\fR
can be given as an option.  If `\fB-\fR' is given as a \fIfile\fR argument,
reports are written on the standard output.  If no options are specified,
\fIrxr\fR writes standard reports on the standard output (equivalent to using
the option \fB-s -\fR).  The output generated by selecting \fB-l\fR or
\fB-L\fR includes column headings only if a \fIfile\fR other than `\fB-\fR' is
specified, and only if the specified \fIfile\fR does not already exist.  In
this way, \fIrxr\fR can be used repeatedly to build up a line-format table for
multiple records, for further processing by \fIsumstats\fR(1).
.PP
The \fB-v\fR option specifies that each mismatch is described on the standard
output in a format similar to:
.br
    3/5(120188-121065)
.br
where the first number is the reference run length, the second is the test
run length (each of these is between 0 and 6), and the numbers in parentheses
indicate the location of the match window in sample intervals.
.PP
The shell variable \fBWFDB\fR should be set and exported (see
\fIsetwfdb\fR(1)).
.SH BUGS
.PP
Since \fIrxr\fR performs multiple passes over its input files, it cannot be
used at the end of a pipe.
.SH SEE ALSO
bxb(1), ecgeval(1), epic(1), mxm(1), setwfdb(1), sumstats(1)
.br
\fIEvaluating ECG Analyzers\fR (in the \fIWFDB Applications Guide\fR)
.br
\fIAmbulatory Electrocardiographs\fR (ANSI/AAMI EC38:1998)
.br
\fITesting and Reporting Performance Results of Cardiac Rhythm and ST
Segment Measurement Algorithms\fR (ANSI/AAMI EC57:1998)
.br
The last two publications are available from AAMI, 3330 Washington Blvd.,
Suite 400, Arlington, VA 22201 USA (http://www.aami.org/).
.SH AUTHOR
George B. Moody (george@mit.edu)
.SH SOURCE
http://www.physionet.org/physiotools/wfdb/app/rxr.c
