#! /bin/bash
# file: dosify		G. Moody		19 November 2013
#			Last revised:		23 December 2015
# Convert expected test results to MS-DOS/MS-Windows format for MinGW, using
# mv, sed, u2d, and bash builtins.

cd expected
if [ ! -e wfdbwhich.out.orig ]
then
    mv wfdbwhich.out wfdbwhich.out.orig
    sed 's+/+\\+;s+\r*$+\r+' <wfdbwhich.out.orig >wfdbwhich.out
fi

for F in lcheck.log-NETFILES lcheck.log-no-NETFILES bxb.out rxr.out psfd.ps test.des test.key
do
    if [ ! -e $F.orig ]
    then
       mv $F $F.orig
       sed 's+\r*$+\r+' < $F.orig > $F
    fi
done

# if [ ! -e ecgeval.out.orig ]
# then
#    mv ecgeval.out ecgeval.out.orig
#    cp ecgeval.out.dos ecgeval.out
# fi

