#!/bin/sh
# file: appcheck		G. Moody	7 September 2001
#
# This script checks the functionality of the WFDB applications in the 'app'
# directory.
#
# Suggestions for additional checks are welcome;  please send them to the
# author (george@mit.edu).

i=libcheck.log
diff -q $i $i-expected &&
     ( echo " Files $i and $i-expected match: test succeeded"
       rm -f $i )
rm -rf mitdb 100s.chk

echo Testing xform ...
xform -i mimicdb/237/237 -s 1 2 0 3 -f 9:19:45 -t "[22:01:23 20/07/1995]" \
 -a all -M -n test -S response >test.log 2>&1
for i in test.log test.hea test.dat test.all
do
	diff -q $i $i-expected &&
	 ( echo " Files $i and $i-expected match: test succeeded"
	   rm -f $i )
done
