.TH RDSAMP 1 "7 November 2002" "WFDB 10.3.0" "WFDB Applications Guide"
.SH NAME
rdsamp \- read WFDB signal files
.SH SYNOPSIS
\fBrdsamp -r\fR \fIrecord\fR [ \fIoptions\fR ... ]
.SH DESCRIPTION
\fBrdsamp\fR reads signal files for the specified \fIrecord\fR and writes the
samples as decimal numbers on the standard output.  If no \fIoptions\fR are
provided, \fBrdsamp\fR starts at the beginning of the record and prints all
samples.  Each line of output contains the sample number and samples from each
signal, beginning with channel 0, separated by tabs.
.PP
\fIOptions\fR include:
.TP
\fB-f\fR \fItime\fR
Begin at the specified \fItime\fR.  By default, \fBrdsamp\fR starts at the
beginning of the record.
.TP
\fB-h\fR
Print a usage summary.
.TP
\fB-H\fR
Read the signal files in high-resolution mode (default: standard mode).
These modes are identical for ordinary records.  For multifrequency records,
the standard decimation of oversampled signals to the frame rate is suppressed
in high-resolution mode (rather, all other signals are resampled at the highest
sampling frequency).
.TP
\fB-l\fR \fIinterval\fR
Limit the amount of output to the specified time \fIinterval\fR (in standard
time format;  default: no limit).  If both \fB-l\fR and \fB-t\fR are used,
\fBrdsamp\fR stops at the earlier of the two limits.
.TP
\fB-p\fR
Print times in seconds and milliseconds, and values in physical units.  By
default, \fBrdsamp\fR prints times in sample intervals and values in A/D units.
Use \fB-p -p\fR to obtain higher precision in the sample values
(8 decimal places rather than 3).
.TP
\fB-s\fR \fIsignal-list\fR
Print only the signals named in the \fIsignal-list\fR (one or more input signal
numbers, separated by spaces;  default: print all signals).  This option may be
used to re-order or duplicate signals.
.TP
\fB-t\fR \fItime\fR
Stop at the specified \fItime\fR.  By default, \fBrdsamp\fR stops at the end
of the record.
.TP
\fB-v\fR
Print column headings.
.SH ENVIRONMENT
.PP
It may be necessary to set and export the shell variable \fBWFDB\fR (see
\fBsetwfdb\fR(1)).
.SH CD-ROM Versions
The first edition of the MIT-BIH Arrhythmia Database CD-ROM, the first and
second editions of the European ST-T Database CD-ROM, and the first edition of
the MIT-BIH Polysomnographic Database CD-ROM contain versions of \fBrdsamp\fR
that use an older command syntax (still supported by the current version but
not described here).  Refer to \fIbin.doc\fR in the CD-ROM directory that
contains \fBrdsamp\fR for further information.
.SH SEE ALSO
\fBrdann\fR(1), \fBsetwfdb\fR(1), \fBwrsamp\fR(1)
.SH AUTHOR
George B. Moody (george@mit.edu)
.SH SOURCE
http://www.physionet.org/physiotools/wfdb/app/rdsamp.c
