.TH SAMPFREQ 1 "31 July 2002" "WFDB 10.2.7" "WFDB Applications Guide"
.SH NAME
sampfreq \- show sampling frequency for a record
.SH SYNOPSIS
\fBsampfreq\fR [ \fB-H\fR ] \fIrecord \fR
.SH DESCRIPTION
This program shows the sampling frequency for the specified \fIrecord\fR.
By default, \fBsampfreq\fR shows the base sampling frequency (frame rate)
for multi-frequency records;  if the \fB-H\fR option is present,
\fBsampfreq\fR shows the highest sampling frequency used for any signal
in a multi-frequency record.
.SH ENVIRONMENT
.PP
It may be necessary to set and export the shell variable \fBWFDB\fR (see
\fBsetwfdb\fR(1)).
.SH FILES
.TP 22
\fIrecord\fR.hea
header file
.SH SEE ALSO
\fBsetwfdb\fR(1)
.SH AUTHOR
George B. Moody (george@mit.edu)
.SH SOURCE
http://www.physionet.org/physiotools/wfdb/app/sampfreq.c
