.TH WFDBDESC 1 "30 May 2002" "WFDB software 10.2.6" "WFDB applications"
.SH NAME
wfdbdesc \- read signal specifications
.SH SYNOPSIS
\fBwfdbdesc\fR \fIrecord\fR [ \fB-readable\fR ]
.SH DESCRIPTION
This program reads specifications for the signals described in the \fIheader\fR
file for \fIrecord\fR.  If the \fB-readable\fR option is present,
\fBwfdbdesc\fR attempts to open the signal files, and it reports only on
those that are readable.
.SH ENVIRONMENT
.PP
It may be necessary to set and export the shell variable \fBWFDB\fR (see
\fBsetwfdb\fR(1)).
.SH FILES
.TP 22
\fIrecord\fR.hea
header file
.TP
signal files
named in \fIrecord\fR.hea
.SH SEE ALSO
\fBsetwfdb\fR(1)
.SH AUTHOR
George B. Moody (george@mit.edu)
.SH SOURCE
http://www.physionet.org/physiotools/wfdb/app/wfdbdesc.c
