#! /bin/sh
# file: wugfigures
#
# Get or remove a set of WAVE User's Guide figures in the wug-src directory.
# The wug-src directory must be the current directory when this script is run.

if [ $# -eq 1 ]; then OPT=$1
else OPT=-grey
fi

case $OPT in
  -clean) for i in wave/ps/*.ps
	  do
	     rm -f `basename $i .ps`.p*
	  done
          for i in wave/ppm/*.ppm.gz
	  do
	     rm -f `basename $i .ppm.gz`.p*
	  done ;;
  -color) for i in wave/ps/*.ps
	  do
	     OUT=`basename $i`
	     if [ ! -s $OUT ]; then
	        cp -f $i $OUT
	        echo $i '-->' $OUT
	     fi
	  done
	  for i in wave/ppm/*.ppm.gz
	  do
	     OUT=`basename $i .ppm.gz`.ps
	     if [ ! -s $OUT ]; then
	        gzip -d <$i | pnmdepth 255 | \
		    pnmtops -noturn -scale .5 >$OUT 2>/dev/null
	        echo $i '-->' $OUT
	     fi
	  done ;;
   -grey) for i in wave/ps/*.ps
	  do
	     OUT=`basename $i`
	     if [ ! -s $OUT ]; then
	        cp -f $i $OUT
	        echo $i '-->' $OUT
	     fi
	  done
	  for i in wave/ppm/*.ppm.gz
	  do
	     OUT=`basename $i .ppm.gz`.ps
	     if [ ! -s $OUT ]; then
	        gzip -d <$i | pnmdepth 255 | ppmtopgm | \
		    pnmtops -noturn -scale .5 >$OUT 2>/dev/null
	        echo $i '-->' $OUT
	     fi
	  done ;;
    -pdf) for i in wave/ps/*.ps
	  do
	     OUT=`basename $i .ps`.pdf
	     if [ ! -s $OUT ]; then
	        epstopdf --filter <$i >$OUT
	        echo $i '-->' $OUT
	     fi
	  done
	  for i in wave/ppm/*.ppm.gz
	  do
	     OUT=`basename $i .ppm.gz`.pdf
	     if [ ! -s $OUT ]; then
	        gzip -d <$i | pnmdepth 255 | \
		    pnmtops -noturn -scale .5 2>/dev/null | \
		    epstopdf --filter --outfile=$OUT
	        echo $i '-->' $OUT
	     fi
	  done ;;
esac
